// Generated by tools/application_routing_policy.py. Do not edit.
#pragma once
#include "saex/engine/application_routing.hpp"
#include "saex/engine/event_dispatch_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_dispatch_digest == "6265420804ada87df4beae0fc034fcb0478ad408dd05d04e9173d6d02f681058");
inline constexpr std::string_view reviewed_routing_id="gta-sa.f01a00ce.application-routing-v1";
inline constexpr std::string_view reviewed_routing_digest="d2794efb7784cb53b20d693533f5ab67c6f05a8fbd4c2d77264942910c408f66";
inline constexpr ApplicationRoutingSpec reviewed_routing_spec{FrameTargetSpec{4194304U,18313216U,1305643U,1293136U,{std::byte{0xe8}, std::byte{0x20}, std::byte{0xcf}, std::byte{0xff}, std::byte{0xff}},{std::byte{0xe8}, std::byte{0x5b}, std::byte{0x38}, std::byte{0x1f}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x26}, std::byte{0x16}, std::byte{0x03}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x91}, std::byte{0xcb}, std::byte{0xff}, std::byte{0xff}, std::byte{0x6a}}},6350U,1305864U,1305820U,{std::byte{0x00}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x01}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x02}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x03}, std::byte{0x04}, std::byte{0x0a}, std::byte{0x05}, std::byte{0x06}, std::byte{0x07}, std::byte{0x08}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x09}},{{1305660U,1305773U,1305761U,1305711U,1305731U,1305643U,1305750U,1305784U,1305803U,1305705U,1305814U}}};
}
