// Generated by tools/application_routing_policy.py. Do not edit.
#pragma once
#include "saex/engine/application_routing.hpp"
#include "saex/engine/event_dispatch_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_dispatch_digest == "77662469d61f491223d64f12e4f4c5176c8a75d871090dd3dd5b6176e9fe3a1d");
inline constexpr std::string_view reviewed_routing_id="gta-sa.f01a00ce.application-routing-v1";
inline constexpr std::string_view reviewed_routing_digest="b97ecbac6dc05cc18e90af42274e1b148e741fc62012cddce98b86a90809e88e";
inline constexpr ApplicationRoutingSpec reviewed_routing_spec{FrameTargetSpec{4194304U,18313216U,1305643U,1293136U,{std::byte{0xe8}, std::byte{0x20}, std::byte{0xcf}, std::byte{0xff}, std::byte{0xff}},{std::byte{0xe8}, std::byte{0x5b}, std::byte{0x38}, std::byte{0x1f}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x26}, std::byte{0x16}, std::byte{0x03}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x91}, std::byte{0xcb}, std::byte{0xff}, std::byte{0xff}, std::byte{0x6a}}},6350U,1305864U,1305820U,{std::byte{0x00}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x01}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x02}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x03}, std::byte{0x04}, std::byte{0x0a}, std::byte{0x05}, std::byte{0x06}, std::byte{0x07}, std::byte{0x08}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x0a}, std::byte{0x09}},{{1305660U,1305773U,1305761U,1305711U,1305731U,1305643U,1305750U,1305784U,1305803U,1305705U,1305814U}}};
}
