// Generated by tools/binding_policy.py. Do not edit.
#pragma once
#include "saex/engine/codec_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_codec_policy_digest == "425272040c068e1e73b0cc1a9c43f9328b4dd13a2a00441efdbebe0a2372348d", "binding codec drift");
inline constexpr std::string_view reviewed_binding_policy_id = "gta-sa.f01a00ce.windows-26200.codec-bindings-v1";
inline constexpr std::string_view reviewed_binding_policy_digest = "92856899cf2250668e1b644d9ec2c111b01e72eba46643bb4631285ee3de84eb";
inline constexpr std::array<BindingSlotSpec, 8> reviewed_binding_slots{{
    BindingSlotSpec{"ov_open_callbacks", 25608, 4352},
    BindingSlotSpec{"ov_clear", 25640, 4096},
    BindingSlotSpec{"ov_time_total", 25620, 8640},
    BindingSlotSpec{"ov_time_tell", 25604, 13296},
    BindingSlotSpec{"ov_read", 25644, 13664},
    BindingSlotSpec{"ov_info", 25628, 13536},
    BindingSlotSpec{"ov_time_seek", 25600, 12720},
    BindingSlotSpec{"ov_time_seek_page", 25636, 12976},
}};
inline constexpr BindingStopSpec reviewed_binding_spec{5446, 16420, {std::byte{0xc7}, std::byte{0x85}, std::byte{0x54}, std::byte{0xfd}, std::byte{0xff}, std::byte{0xff}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0xc7}, std::byte{0x85}, std::byte{0x58}, std::byte{0xfd}, std::byte{0xff}, std::byte{0xff}}, reviewed_binding_slots};
}
