// Generated by tools/bootstrap_lifecycle_policy.py. Do not edit.
#pragma once
#include "saex/engine/asi_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_asi_policy_digest == "ac29aeefa1b2a2ccb54777a9c96ee40248f90b244c51e0587eca8912664407c7", "Bootstrap ASI drift");
static_assert(bootstrap_call_sequence == std::array<std::uint32_t,8>{1,0,1,0,2,1,0,2});
inline constexpr std::string_view reviewed_bootstrap_policy_id = "gta-sa.f01a00ce.windows-26200-9445.bootstrap-lifecycle-v1";
inline constexpr std::string_view reviewed_bootstrap_policy_digest = "8bb3a30af35985c8b9d0f86612ec54a6d625d0b799739b395c124e38245f28d4";
inline constexpr LoaderPinSpec reviewed_bootstrap_crypto_pin{LoaderOrigin::system_x86, "bcryptprimitives.dll", 501136ULL, {std::byte{0xdf}, std::byte{0xd2}, std::byte{0x9f}, std::byte{0x2c}, std::byte{0x1f}, std::byte{0x28}, std::byte{0x03}, std::byte{0x49}, std::byte{0x49}, std::byte{0xf0}, std::byte{0xa3}, std::byte{0x71}, std::byte{0x6a}, std::byte{0x99}, std::byte{0xf0}, std::byte{0x08}, std::byte{0x16}, std::byte{0xbd}, std::byte{0xa0}, std::byte{0xbf}, std::byte{0xfd}, std::byte{0x48}, std::byte{0xa5}, std::byte{0xa2}, std::byte{0x75}, std::byte{0x0b}, std::byte{0xe4}, std::byte{0x56}, std::byte{0x9e}, std::byte{0x7d}, std::byte{0x21}, std::byte{0xee}}};
}
