// Generated by tools/bootstrap_lifecycle_policy.py. Do not edit.
#pragma once
#include "saex/engine/asi_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_asi_policy_digest == "42947538ada61d7a163ff3a085c17b5218a8d702a7fe44445cfd2a2be154b1e8", "Bootstrap ASI drift");
static_assert(bootstrap_call_sequence == std::array<std::uint32_t,8>{1,0,1,0,2,1,0,2});
inline constexpr std::string_view reviewed_bootstrap_policy_id = "gta-sa.f01a00ce.windows-26200.bootstrap-lifecycle-v1";
inline constexpr std::string_view reviewed_bootstrap_policy_digest = "cd6f7822e4916a1082ec502cc24e45915cefd0e78f5e17eb894655f17443948e";
inline constexpr LoaderPinSpec reviewed_bootstrap_crypto_pin{LoaderOrigin::system_x86, "bcryptprimitives.dll", 501112ULL, {std::byte{0xc0}, std::byte{0xfb}, std::byte{0xa4}, std::byte{0x40}, std::byte{0x6b}, std::byte{0xf9}, std::byte{0xca}, std::byte{0x90}, std::byte{0x9f}, std::byte{0x6f}, std::byte{0x46}, std::byte{0x3f}, std::byte{0x08}, std::byte{0x18}, std::byte{0x9d}, std::byte{0x6e}, std::byte{0xb4}, std::byte{0x72}, std::byte{0x38}, std::byte{0xd7}, std::byte{0xbb}, std::byte{0x59}, std::byte{0x0d}, std::byte{0x58}, std::byte{0x34}, std::byte{0x4a}, std::byte{0xf8}, std::byte{0xca}, std::byte{0xdd}, std::byte{0x6b}, std::byte{0xda}, std::byte{0x8e}}};
}
