// Generated by tools/cd_stream_allocation_policy.py. Do not edit.
#pragma once
#include "saex/engine/cd_stream_allocation.hpp"
#include "saex/engine/cd_stream_disk_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cd_stream_disk_digest=="64b5b07022d33654019d74ba6ec3deaa623f23bcac972280487962234782beb3");
inline constexpr std::string_view reviewed_cd_stream_allocation_id="gta-sa.f01a00ce.cd-stream-allocation-v1";
inline constexpr std::string_view reviewed_cd_stream_allocation_digest="c0a0bc0d4a617c5b02d44fe54f7639a79a7728fe4aa3ec67160fe8cd2aa31391";
inline constexpr CdStreamAllocationSpec reviewed_cd_stream_allocation_spec{4342359U,4342315U,4342192U,4751432U,9022924U,9028324U,9028340U,9028344U,4555256U,4342303U,BootstrapExportSpec{260224U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x6a}, std::byte{0xfe}, std::byte{0x68}, std::byte{0x68}, std::byte{0xe5}, std::byte{0x39}, std::byte{0x4b}, std::byte{0x68}, std::byte{0x80}, std::byte{0x25}, std::byte{0x30}, std::byte{0x4b}, std::byte{0x64}, std::byte{0xa1}, std::byte{0x00}},1260912640U,8448U}};
}
