// Generated by tools/cd_stream_tables_policy.py. Do not edit.
#pragma once
#include "saex/engine/cd_stream_tables.hpp"
#include "saex/engine/file_manager_ready_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_file_manager_ready_digest=="44d7fb56bdba33282749287b1b3a78417c8d0d3d24549ed707c47d32955fe013");
inline constexpr std::string_view reviewed_cd_stream_tables_id="gta-sa.f01a00ce.cd-stream-tables-v1";
inline constexpr std::string_view reviewed_cd_stream_tables_digest="cf13c6732681f4b2a33f0e8c74c1f12d2a1f5c37975dd9c387ebec361b477aa3";
inline constexpr CdStreamTablesSpec reviewed_cd_stream_tables_spec{27504U,5128208U,5128344U,4554944U};
}
