// Generated by tools/cd_stream_disk_policy.py. Do not edit.
#pragma once
#include "saex/engine/cd_stream_disk.hpp"
#include "saex/engine/cd_stream_tables_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cd_stream_tables_digest=="cf13c6732681f4b2a33f0e8c74c1f12d2a1f5c37975dd9c387ebec361b477aa3");
inline constexpr std::string_view reviewed_cd_stream_disk_id="gta-sa.f01a00ce.cd-stream-disk-v1";
inline constexpr std::string_view reviewed_cd_stream_disk_digest="64b5b07022d33654019d74ba6ec3deaa623f23bcac972280487962234782beb3";
inline constexpr CdStreamDiskSpec reviewed_cd_stream_disk_spec{5128160U,3339456U,125856U,529236U,BootstrapExportSpec{2366448U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x51}, std::byte{0x51}, std::byte{0x83}, std::byte{0x7d}, std::byte{0x08}, std::byte{0x00}, std::byte{0x8d}, std::byte{0x4d}, std::byte{0xf8}, std::byte{0xba}, std::byte{0xb4}, std::byte{0x23}, std::byte{0x0c}, std::byte{0x10}, std::byte{0x0f}},268435456U,32768U}};
}
