// Generated by tools/codec_policy.py. Do not edit.
#pragma once
#include "saex/engine/startup_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_startup_policy_digest == "ed2834167df81d2068197dd333e7f28602dc243adcd8d80290498c41508caf30", "codec startup drift");
inline constexpr std::string_view reviewed_codec_policy_id = "gta-sa.f01a00ce.windows-26200.codec-return-v1";
inline constexpr std::string_view reviewed_codec_policy_digest = "425272040c068e1e73b0cc1a9c43f9328b4dd13a2a00441efdbebe0a2372348d";
inline constexpr std::array<std::string_view, 3> reviewed_codec_modules{"vorbishooked.dll", "vorbis.dll", "ogg.dll"};
inline constexpr auto reviewed_codec_specs = [] {
    std::array<LoaderPinSpec, reviewed_entry_specs.size() + 3> result{};
    for (std::size_t i = 0; i < reviewed_entry_specs.size(); ++i) result[i] = reviewed_entry_specs[i];
    result[reviewed_entry_specs.size() + 0] = LoaderPinSpec{LoaderOrigin::game_root, "vorbishooked.dll", 65536ULL, {std::byte{0xa0}, std::byte{0x89}, std::byte{0x23}, std::byte{0x47}, std::byte{0x90}, std::byte{0x00}, std::byte{0xce}, std::byte{0xc3}, std::byte{0x66}, std::byte{0x96}, std::byte{0x7f}, std::byte{0xb8}, std::byte{0x25}, std::byte{0x9e}, std::byte{0x09}, std::byte{0x20}, std::byte{0xb7}, std::byte{0xaa}, std::byte{0x18}, std::byte{0x85}, std::byte{0x97}, std::byte{0x22}, std::byte{0xc7}, std::byte{0xdd}, std::byte{0xa1}, std::byte{0x41}, std::byte{0x57}, std::byte{0x26}, std::byte{0xbe}, std::byte{0xd4}, std::byte{0x77}, std::byte{0x4f}}};
    result[reviewed_entry_specs.size() + 1] = LoaderPinSpec{LoaderOrigin::game_root, "vorbis.dll", 1060864ULL, {std::byte{0xfe}, std::byte{0xfd}, std::byte{0xa8}, std::byte{0x50}, std::byte{0xb6}, std::byte{0x9e}, std::byte{0x00}, std::byte{0x7f}, std::byte{0xce}, std::byte{0xba}, std::byte{0x64}, std::byte{0x44}, std::byte{0x83}, std::byte{0xc7}, std::byte{0x61}, std::byte{0x6b}, std::byte{0xc0}, std::byte{0x7e}, std::byte{0x9f}, std::byte{0x17}, std::byte{0x7f}, std::byte{0xc6}, std::byte{0x34}, std::byte{0xfb}, std::byte{0x74}, std::byte{0xe1}, std::byte{0x14}, std::byte{0xf0}, std::byte{0xd1}, std::byte{0x5b}, std::byte{0x0d}, std::byte{0xb0}}};
    result[reviewed_entry_specs.size() + 2] = LoaderPinSpec{LoaderOrigin::game_root, "ogg.dll", 36864ULL, {std::byte{0x4a}, std::byte{0x4f}, std::byte{0x65}, std::byte{0x42}, std::byte{0x7e}, std::byte{0x01}, std::byte{0x6b}, std::byte{0x3c}, std::byte{0x5a}, std::byte{0xe0}, std::byte{0xd2}, std::byte{0x51}, std::byte{0x7a}, std::byte{0x69}, std::byte{0xdb}, std::byte{0x5f}, std::byte{0x1c}, std::byte{0xdc}, std::byte{0x7a}, std::byte{0x43}, std::byte{0xd2}, std::byte{0xc0}, std::byte{0xa7}, std::byte{0x95}, std::byte{0x7e}, std::byte{0x8d}, std::byte{0xa5}, std::byte{0xd6}, std::byte{0xf3}, std::byte{0x78}, std::byte{0xf0}, std::byte{0x63}}};
    return result;
}();
inline constexpr CodecStopSpec reviewed_codec_spec{5293, 16836, 16416, "vorbishooked", {}};
}
