// Generated by tools/cwd_query_policy.py. Do not edit.
#pragma once
#include "saex/engine/cwd_query.hpp"
#include "saex/engine/cwd_acquire_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cwd_acquire_digest == "d082f21922b19c205d17a209666d8d862fe7991ffd5ce33305d9a5e2020055df");
inline constexpr std::string_view reviewed_cwd_query_id="gta-sa.f01a00ce.cwd-query-v1";
inline constexpr std::string_view reviewed_cwd_query_digest="8f676b4bfedba10a41fe041b9d80b1f4aa94e71969d7ac25a5c9e138b87dc289";
inline constexpr CwdQuerySpec reviewed_cwd_query_spec{4418979U,5124540U,4555332U,530324U,BootstrapExportSpec{200800U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x5d}, std::byte{0xff}, std::byte{0x25}, std::byte{0x94}, std::byte{0x17}, std::byte{0x08}, std::byte{0x10}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}},268435456U,256U},BootstrapExportSpec{2463152U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x81}, std::byte{0xec}, std::byte{0x1c}, std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0xa1}, std::byte{0xc0}, std::byte{0x3c}, std::byte{0x28}, std::byte{0x10}, std::byte{0x33}, std::byte{0xc5}, std::byte{0x89}, std::byte{0x45}},268435456U,4096U},{std::byte{0x85}, std::byte{0xc0}, std::byte{0x74}, std::byte{0xac}, std::byte{0x40}, std::byte{0x3d}, std::byte{0x04}, std::byte{0x01}, std::byte{0x00}, std::byte{0x00}, std::byte{0x77}, std::byte{0xa4}, std::byte{0x8b}, std::byte{0x4d}, std::byte{0x0c}, std::byte{0x85}}};
}
