// Generated by tools/cwd_return_policy.py. Do not edit.
#pragma once
#include "saex/engine/cwd_return.hpp"
#include "saex/engine/cwd_copy_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cwd_copy_digest == "4ea42b0e0ece7ba1ba21a620ff1f85d6bd48b8f21247f30f25a9d21ffacdbe94");
inline constexpr std::string_view reviewed_cwd_return_id="gta-sa.f01a00ce.cwd-return-v1";
inline constexpr std::string_view reviewed_cwd_return_digest="46e4f2c0b9ba2217ae1eb7d54927306e97c0f653ee04a0ee16105799b1ba1bdb";
inline constexpr CwdReturnSpec reviewed_cwd_return_spec{4369108U,{std::byte{0x83}, std::byte{0xc4}, std::byte{0x0c}, std::byte{0x89}, std::byte{0x45}, std::byte{0xe4}, std::byte{0x83}, std::byte{0x4d}, std::byte{0xfc}, std::byte{0xff}, std::byte{0xe8}, std::byte{0x09}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x8b}}};
}
