// Generated by tools/cwd_copy_policy.py. Do not edit.
#pragma once
#include "saex/engine/cwd_copy.hpp"
#include "saex/engine/cwd_query_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cwd_query_digest == "8f676b4bfedba10a41fe041b9d80b1f4aa94e71969d7ac25a5c9e138b87dc289");
inline constexpr std::string_view reviewed_cwd_copy_id="gta-sa.f01a00ce.cwd-copy-v1";
inline constexpr std::string_view reviewed_cwd_copy_digest="4ea42b0e0ece7ba1ba21a620ff1f85d6bd48b8f21247f30f25a9d21ffacdbe94";
inline constexpr CwdCopySpec reviewed_cwd_copy_spec{4351376U,{std::byte{0x59}, std::byte{0x59}, std::byte{0xe9}, std::byte{0x51}, std::byte{0xff}, std::byte{0xff}, std::byte{0xff}, std::byte{0x6a}, std::byte{0x0c}, std::byte{0x68}, std::byte{0x18}, std::byte{0xdf}, std::byte{0x88}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x43}}};
}
