// Generated by tools/file_manager_ready_policy.py. Do not edit.
#pragma once
#include "saex/engine/file_manager_ready.hpp"
#include "saex/engine/cwd_return_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_cwd_return_digest == "46e4f2c0b9ba2217ae1eb7d54927306e97c0f653ee04a0ee16105799b1ba1bdb");
inline constexpr std::string_view reviewed_file_manager_ready_id="gta-sa.f01a00ce.file-manager-ready-v1";
inline constexpr std::string_view reviewed_file_manager_ready_digest="44d7fb56bdba33282749287b1b3a78417c8d0d3d24549ed707c47d32955fe013";
inline constexpr FileManagerReadySpec reviewed_file_manager_ready_spec{4369682U,4554984U,4359963U,BootstrapExportSpec{341088U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x83}, std::byte{0xec}, std::byte{0x08}, std::byte{0x53}, std::byte{0x56}, std::byte{0x8b}, std::byte{0x75}, std::byte{0x08}, std::byte{0x57}, std::byte{0x83}, std::byte{0x46}, std::byte{0x08}, std::byte{0xff}, std::byte{0x0f}, std::byte{0x85}},1260912640U,0U}};
}
