// Generated by tools/file_manager_entry_policy.py. Do not edit.
#pragma once
#include "saex/engine/file_manager_entry.hpp"
#include "saex/engine/game_prelude_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_prelude_digest == "ab85c8782ca66f94bd52dc6137452c6b07aed12b38725f76b788240bf82c7bc6");
inline constexpr std::string_view reviewed_file_manager_id="gta-sa.f01a00ce.file-manager-entry-v1";
inline constexpr std::string_view reviewed_file_manager_digest="a7dfec624fcba478c2d9fa69ba34f2f78c33ed5d66f00fa3427a63aa4cfb536b";
inline constexpr FileManagerEntrySpec reviewed_file_manager_spec{FrameTargetSpec{4194304U,18313216U,1293146U,1279728U,{std::byte{0xe8}, std::byte{0x91}, std::byte{0xcb}, std::byte{0xff}, std::byte{0xff}},{std::byte{0x57}, std::byte{0x68}, std::byte{0x80}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x68}, std::byte{0xe0}, std::byte{0x1a}, std::byte{0xb7}, std::byte{0x00}, std::byte{0xe8}, std::byte{0x91}, std::byte{0xe7}, std::byte{0x2f}, std::byte{0x00}}},4419217U,7805664U,4562812U,{std::byte{0x6a}, std::byte{0x05}, std::byte{0xe8}, std::byte{0x0a}, std::byte{0xb0}, std::byte{0xec}, std::byte{0xff}, std::byte{0x83}, std::byte{0xc4}, std::byte{0x04}, std::byte{0xe8}, std::byte{0x22}, std::byte{0x62}, std::byte{0x00}, std::byte{0x00}, std::byte{0xb0}}};
}
