// Generated by tools/frame_target_policy.py. Do not edit.
#pragma once
#include "saex/engine/frame_target.hpp"
#include "saex/engine/bootstrap_lifecycle_policy.generated.hpp"
#include "saex/engine/observed_profile.generated.hpp"
namespace saex::engine {
static_assert(reviewed_bootstrap_policy_digest == "cd6f7822e4916a1082ec502cc24e45915cefd0e78f5e17eb894655f17443948e");
static_assert(observed_profile_source_digest == "0653426a913c3fdef809ea9e6a614fca7d26498e66cb63148d7073fe8d965436");
inline constexpr std::string_view reviewed_frame_policy_id = "gta-sa.f01a00ce.frame-candidate-v1";
inline constexpr std::string_view reviewed_frame_policy_digest = "03b425ca10f2187fdc11a635798ccca269b8716c36bfe3f06a41e0f19315794d";
inline constexpr FrameTargetSpec reviewed_frame_spec{4194304U, 18313216U, 1304961U, 1294048U, {std::byte{0xe8}, std::byte{0x5a}, std::byte{0xd5}, std::byte{0xff}, std::byte{0xff}}, {std::byte{0x83}, std::byte{0xec}, std::byte{0x0c}, std::byte{0x53}, std::byte{0x56}, std::byte{0x57}, std::byte{0xe8}, std::byte{0xe5}, std::byte{0x5e}, std::byte{0x00}, std::byte{0x00}, std::byte{0xb9}, std::byte{0x78}, std::byte{0x29}, std::byte{0xb7}, std::byte{0x00}}};
}
