// Generated by tools/engine_profiles.py; do not edit.
#pragma once
#include "saex/engine/profile_gate.hpp"
namespace saex::engine {
inline constexpr std::string_view observed_profile_source_digest = "0653426a913c3fdef809ea9e6a614fca7d26498e66cb63148d7073fe8d965436";
inline constexpr PeLayout observed_layout = [] {
    PeLayout l{};
    l.timestamp = 1114702282U;
    l.image_base = 4194304U;
    l.entry_rva = 4343152U;
    l.image_size = 18313216U;
    l.headers_size = 1024U;
    l.section_alignment = 4096U;
    l.file_alignment = 512U;
    l.characteristics = 303U;
    l.dll_characteristics = 0U;
    l.section_count = 11;
    l.sections[0] = PeSection{{'.', 't', 'e', 'x', 't'}, 4546560U, 4096U, 4546048U, 1024U, 1610612768U};
    l.sections[1] = PeSection{{'_', 'r', 'w', 'c', 's', 'e', 'g'}, 4096U, 4550656U, 1536U, 4547072U, 1610612768U};
    l.sections[2] = PeSection{{'.', 'r', 'd', 'a', 't', 'a'}, 311296U, 4554752U, 308224U, 4548608U, 1073741888U};
    l.sections[3] = PeSection{{'.', 'd', 'a', 't', 'a'}, 4169728U, 4866048U, 262144U, 4856832U, 3221225536U};
    l.sections[4] = PeSection{{'_', 'T', 'E', 'X', 'T', '_', 'H', 'A'}, 69632U, 9035776U, 68608U, 5118976U, 3221225536U};
    l.sections[5] = PeSection{{'_', 'r', 'w', 'd', 's', 'e', 'g'}, 4096U, 9105408U, 512U, 5187584U, 3221225536U};
    l.sections[6] = PeSection{{'.', 'r', 's', 'r', 'c'}, 4096U, 9109504U, 1536U, 5188096U, 1073741888U};
    l.sections[7] = PeSection{{'.', 't', 'e', 'x', 't'}, 6594560U, 9113600U, 6593536U, 5189632U, 3758096416U};
    l.sections[8] = PeSection{{'.', 'i', 'n', 'i', 't'}, 24576U, 15708160U, 23040U, 11783168U, 3758096416U};
    l.sections[9] = PeSection{{'.', 'd', 'a', 't', 'a'}, 2445312U, 15732736U, 2442240U, 11806208U, 3758096448U};
    l.sections[10] = PeSection{{'.', 'H', 'O', 'O', 'D', 'L', 'U', 'M'}, 135168U, 18178048U, 135168U, 14248448U, 3758096416U};
    return l;
}();
inline constexpr std::array<ImageAnchor, 4> observed_anchors{{
    ImageAnchor{"version-marker", 4096U, 0, 5, {std::byte{0xe9}, std::byte{0x7b}, std::byte{0x19}, std::byte{0x16}, std::byte{0x01}}},
    ImageAnchor{"game-process-call", 1304961U, 0, 5, {std::byte{0xe8}, std::byte{0x5a}, std::byte{0xd5}, std::byte{0xff}, std::byte{0xff}}},
    ImageAnchor{"init-game-call", 3443963U, 0, 5, {std::byte{0xe8}, std::byte{0x80}, std::byte{0x58}, std::byte{0xdf}, std::byte{0xff}}},
    ImageAnchor{"shutdown-rw-call", 1300752U, 0, 5, {std::byte{0xe8}, std::byte{0x6b}, std::byte{0xe2}, std::byte{0xff}, std::byte{0xff}}},
}};
inline constexpr ObservedProfile observed_profile{"gta-sa.observed.f01a00ce950fa40c", 14383616U, {std::byte{0xf0}, std::byte{0x1a}, std::byte{0x00}, std::byte{0xce}, std::byte{0x95}, std::byte{0x0f}, std::byte{0xa4}, std::byte{0x0c}, std::byte{0xa1}, std::byte{0xed}, std::byte{0x59}, std::byte{0xdf}, std::byte{0x0e}, std::byte{0x78}, std::byte{0x98}, std::byte{0x48}, std::byte{0xc6}, std::byte{0xed}, std::byte{0xcf}, std::byte{0x64}, std::byte{0x05}, std::byte{0x45}, std::byte{0x62}, std::byte{0x74}, std::byte{0x96}, std::byte{0x58}, std::byte{0x85}, std::byte{0xd0}, std::byte{0x92}, std::byte{0x93}, std::byte{0x43}, std::byte{0xac}}, observed_layout, observed_anchors};
}
