// Generated by tools/proxy_policy.py. Do not edit.
#pragma once
#include "saex/engine/entry_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_entry_policy_digest == "56328c7da0b0de6f3584e526b5fae3484634af927ce3a2cc8ace311112166cb2", "proxy policy entry drift");
inline constexpr std::string_view reviewed_proxy_policy_id = "gta-sa.f01a00ce.windows-26200.proxy-return-v1";
inline constexpr std::string_view reviewed_proxy_policy_digest = "20ff7fb664b56f3a43cded86faaa15743495e0cc1d9f17ccb675ccf6732fddcf";
inline constexpr std::string_view reviewed_proxy_module = "vorbisfile.dll";
inline constexpr ProxyStopSpec reviewed_proxy_spec{nullptr, 7520, 7136, 25624, 4555248, 7072};
}
