// Generated by tools/startup_return_policy.py. Do not edit.
#pragma once
#include "saex/engine/startup_return.hpp"
#include "saex/engine/frame_target_policy.generated.hpp"
namespace saex::engine {
static_assert(reviewed_frame_policy_digest == "8bfb3b0974dc2222b6459eb2a323516ce08b568c8f59412aacdb2c9993810d0b");
static_assert(startup_image_protections == std::array<std::uint32_t,2>{64,128});
inline constexpr std::string_view reviewed_startup_return_id = "gta-sa.f01a00ce.windows-26200-9445.startup-return-v1";
inline constexpr std::string_view reviewed_startup_return_digest = "497aece5ffd9a9e82c61a7148cfddef5e35ed60ed771e6b82d11f7a99573fe4f";
inline constexpr StartupReturnSpec reviewed_startup_return_spec{6989U,16396U,16424U,7097U,{std::byte{0x8b}, std::byte{0x4d}, std::byte{0xf4}, std::byte{0x64}, std::byte{0x89}, std::byte{0x0d}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x59}, std::byte{0x5f}, std::byte{0x5e}, std::byte{0x8b}, std::byte{0x4d}, std::byte{0xf0}},BootstrapExportSpec{92976U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x5d}, std::byte{0xff}, std::byte{0x25}, std::byte{0x8c}, std::byte{0x16}, std::byte{0x08}, std::byte{0x10}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}, std::byte{0xcc}},268435456U,256U},BootstrapExportSpec{410912U,{std::byte{0x8b}, std::byte{0xff}, std::byte{0x55}, std::byte{0x8b}, std::byte{0xec}, std::byte{0x64}, std::byte{0xa1}, std::byte{0x30}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x83}, std::byte{0xec}, std::byte{0x18}, std::byte{0x53}, std::byte{0x8b}, std::byte{0x58}, std::byte{0x10}, std::byte{0x56}, std::byte{0x8b}},268435456U,0U},reviewed_frame_spec};
}
