using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

if (args.Length is < 1 or > 2 || (args.Length == 2 && args[1] != "--check"))
{
    Console.Error.WriteLine("Usage: ContractGen <repository-root> [--check]");
    return 2;
}
try
{
    var root = Path.GetFullPath(args[0]);
    using var schema = JsonDocument.Parse(File.ReadAllBytes(Path.Combine(root, "contracts/foundation.schema.json")));
    var source = schema.RootElement;
    if (source.GetProperty("schemaVersion").GetInt32() != 1) throw new InvalidDataException("Unknown schema version");
    var ids = source.GetProperty("ids").EnumerateArray().Select(x => x.GetString()!).ToArray();
    var fields = source.GetProperty("entityRefFields").EnumerateArray().Select(x => x.GetString()!).ToArray();
    if (ids.Length is < 1 or > 64 || ids.Distinct(StringComparer.Ordinal).Count() != ids.Length ||
        ids.Any(x => x is null || !Regex.IsMatch(x, "^[A-Z][A-Za-z0-9]{0,63}$")) ||
        fields.Length != 4 || fields.Distinct().Count() != 4 || fields.Any(x => !ids.Contains(x)))
        throw new InvalidDataException("Invalid identifiers/EntityRef schema");
    var fixture = source.GetProperty("fixture");
    var version = fixture.GetProperty("version").GetUInt16();
    var magic = fixture.GetProperty("magic").GetUInt32();
    if (version != 1 || fixture.GetProperty("maxPayloadBytes").GetInt32() != fields.Length * 8)
        throw new InvalidDataException("Unsupported fixture layout");

    var cpp = new StringBuilder("// Generated by ContractGen. Edit contracts/foundation.schema.json.\n#pragma once\n#include <saex/contracts/strong_id.hpp>\n\nnamespace saex::contracts {\n");
    foreach (var id in ids) cpp.Append($"struct {id}Tag;\nusing {id} = StrongId<{id}Tag>;\n");
    cpp.Append("struct EntityRef final {\n");
    foreach (var field in fields) cpp.Append($"    {field} {char.ToLowerInvariant(field[0]) + field[1..]}{{}};\n");
    cpp.Append("    constexpr auto operator<=>(const EntityRef&) const noexcept = default;\n    [[nodiscard]] constexpr bool valid() const noexcept { return ");
    cpp.Append(string.Join(" && ", fields.Select(x => char.ToLowerInvariant(x[0]) + x[1..] + ".value != 0")));
    cpp.Append("; }\n};\n");
    cpp.Append($"inline constexpr std::uint32_t fixture_magic = {magic}U;\ninline constexpr std::uint16_t fixture_version = {version};\ninline constexpr std::uint32_t fixture_payload_bytes = 32;\n}} // namespace saex::contracts\n");

    var cs = new StringBuilder("// Generated by ContractGen. Edit contracts/foundation.schema.json.\nnamespace Saex.Contracts;\n\n");
    foreach (var id in ids) cs.Append($"public readonly record struct {id}(ulong Value);\n");
    cs.Append("public readonly record struct EntityRef(" + string.Join(", ", fields.Select(x => x + " " + x)) + ")\n{\n    public bool IsValid => ");
    cs.Append(string.Join(" && ", fields.Select(x => x + ".Value != 0")) + ";\n}\n");
    cs.Append($"public static class FoundationContract\n{{\n    public const uint FixtureMagic = {magic}U;\n    public const ushort FixtureVersion = {version};\n    public const int PayloadBytes = 32;\n}}\n");
    var files = new Dictionary<string, string>
    {
        ["include/saex/contracts/foundation.generated.hpp"] = cpp.ToString(),
        ["managed/Saex.Contracts/Foundation.Generated.cs"] = cs.ToString()
    };
    foreach (var (relative, content) in files)
    {
        var path = Path.Combine(root, relative);
        if (args.Length == 2)
        {
            if (!File.Exists(path) || File.ReadAllText(path).Replace("\r\n", "\n") != content)
                throw new InvalidDataException($"Generated contract is stale: {relative}");
        }
        else
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }
    }
    Console.WriteLine(args.Length == 2 ? "Generated contracts verified." : "Generated C++ and C# foundation contracts.");
    return 0;
}
catch (Exception error) when (error is IOException or JsonException or InvalidOperationException or KeyNotFoundException or ArgumentException or OverflowException)
{
    Console.Error.WriteLine(error.Message);
    return 1;
}
