// Generated by ContractGen. Edit contracts/foundation.schema.json.
#pragma once
#include <saex/contracts/strong_id.hpp>

namespace saex::contracts {
struct WorldIdTag;
using WorldId = StrongId<WorldIdTag>;
struct WorldEpochTag;
using WorldEpoch = StrongId<WorldEpochTag>;
struct EntityIdTag;
using EntityId = StrongId<EntityIdTag>;
struct GenerationTag;
using Generation = StrongId<GenerationTag>;
struct SessionIdTag;
using SessionId = StrongId<SessionIdTag>;
struct ResourceEpochTag;
using ResourceEpoch = StrongId<ResourceEpochTag>;
struct OwnerEpochTag;
using OwnerEpoch = StrongId<OwnerEpochTag>;
struct ClockDomainIdTag;
using ClockDomainId = StrongId<ClockDomainIdTag>;
struct SimulationTickTag;
using SimulationTick = StrongId<SimulationTickTag>;
struct StateRevisionTag;
using StateRevision = StrongId<StateRevisionTag>;
struct CatalogRevisionTag;
using CatalogRevision = StrongId<CatalogRevisionTag>;
struct SequenceTag;
using Sequence = StrongId<SequenceTag>;
struct EntityRef final {
    WorldId worldId{};
    WorldEpoch worldEpoch{};
    EntityId entityId{};
    Generation generation{};
    constexpr auto operator<=>(const EntityRef&) const noexcept = default;
    [[nodiscard]] constexpr bool valid() const noexcept { return worldId.value != 0 && worldEpoch.value != 0 && entityId.value != 0 && generation.value != 0; }
};
inline constexpr std::uint32_t fixture_magic = 1480933715U;
inline constexpr std::uint16_t fixture_version = 1;
inline constexpr std::uint32_t fixture_payload_bytes = 32;
} // namespace saex::contracts
