// Generated by ContractGen. Edit contracts/foundation.schema.json.
namespace Saex.Contracts;

public readonly record struct WorldId(ulong Value);
public readonly record struct WorldEpoch(ulong Value);
public readonly record struct EntityId(ulong Value);
public readonly record struct Generation(ulong Value);
public readonly record struct SessionId(ulong Value);
public readonly record struct ResourceEpoch(ulong Value);
public readonly record struct OwnerEpoch(ulong Value);
public readonly record struct ClockDomainId(ulong Value);
public readonly record struct SimulationTick(ulong Value);
public readonly record struct StateRevision(ulong Value);
public readonly record struct CatalogRevision(ulong Value);
public readonly record struct Sequence(ulong Value);
public readonly record struct EntityRef(WorldId WorldId, WorldEpoch WorldEpoch, EntityId EntityId, Generation Generation)
{
    public bool IsValid => WorldId.Value != 0 && WorldEpoch.Value != 0 && EntityId.Value != 0 && Generation.Value != 0;
}
public static class FoundationContract
{
    public const uint FixtureMagic = 1480933715U;
    public const ushort FixtureVersion = 1;
    public const int PayloadBytes = 32;
}
