"""Compile the reviewed event-24 detour and indirect route; initializer remains forbidden."""
import argparse, hashlib, json, re, struct
from pathlib import Path
import event_dispatch_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/application-routing-policy.json')
OUTPUT=Path('include/saex/engine/application_routing_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('routing_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','dispatchPolicySha256','reviewDocument','initializer','detourRva','indexRva','tableRva','indicesHex','targetRvas','detourHex','indirectHex'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('routing_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-game-initializer-call':raise ValueError('routing_identity')
    if p['dispatchPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('routing_parent')
    if p['reviewDocument']!='docs/development/d1-application-routing.md':raise ValueError('routing_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout']
    size=layout['imageSize'];base=layout['imageBase'];dispatch=json.loads(parents[0]);app=dispatch['application'];f=p['initializer']
    if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('routing_frame')
    def region(r,n,code):
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&(0x20000000 if code else 0x40000000) for s in layout['sections']):raise ValueError('routing_range')
    def hexval(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(n*2)+'}',v):raise ValueError('routing_hex')
        return bytes.fromhex(v)
    region(f['callRva'],5,True);region(f['targetRva'],16,True)
    call=hexval(f['callHex'],5);hexval(f['targetPrefixHex'],16)
    if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']:raise ValueError('routing_call')
    region(p['detourRva'],12,True);region(p['indexRva'],39,False);region(p['tableRva'],44,False)
    indices=hexval(p['indicesHex'],39);targets=p['targetRvas']
    if type(targets) is not list or len(targets)!=11:raise ValueError('routing_table')
    for r in targets:region(r,1,True)
    if max(indices)>10 or indices[24]!=5 or targets[5]!=f['callRva']:raise ValueError('routing_selection')
    word=lambda n:struct.pack('<I',n&0xffffffff)
    r=app['targetRva']
    entry=b'\x8b\x44\x24\x04\x83\xf8\x26\x0f\x87'+word(targets[10]-r-13)+b'\x90\x90\xe9'+word(p['detourRva']-r-20)+b'\xff'
    if entry.hex()!=dispatch['applicationPrefixHex']:raise ValueError('routing_entry')
    detour=b'\x0f\xb6\x80'+word(base+p['indexRva'])+b'\xe9'+word(r+20-p['detourRva']-12)
    indirect=b'\xff\x24\x85'+word(base+p['tableRva'])
    if hexval(p['detourHex'],12)!=detour or hexval(p['indirectHex'],7)!=indirect:raise ValueError('routing_operands')
    spans=[(r,27),(p['detourRva'],12),(p['indexRva'],39),(p['tableRva'],44),(f['callRva'],5),(f['targetRva'],16),(dispatch['dispatcher']['targetRva'],17),(dispatch['dispatcher']['callRva']-7,12)]
    region(r,27,True)
    for i,(r,n) in enumerate(spans):
        if any(r<q+m and q<r+n for q,m in spans[:i]):raise ValueError('routing_overlap')
    frame=f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,'+byte_array(f['callHex'])+','+byte_array(f['targetPrefixHex'])+'}'
    return '\n'.join(['// Generated by tools/application_routing_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/application_routing.hpp"','#include "saex/engine/event_dispatch_policy.generated.hpp"',
        'namespace saex::engine {',f'static_assert(reviewed_dispatch_digest == "{p["dispatchPolicySha256"]}");',
        f'inline constexpr std::string_view reviewed_routing_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_routing_digest="{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr ApplicationRoutingSpec reviewed_routing_spec{'+frame+f',{p["detourRva"]}U,{p["indexRva"]}U,{p["tableRva"]}U,'+byte_array(p['indicesHex'])+',{{'+','.join(f'{r}U' for r in targets)+'}}};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('routing_size')
    if not (ROOT/'docs/development/d1-application-routing.md').is_file():raise ValueError('routing_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_routing_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Application routing policy verified.' if a.check else 'Application routing policy generated.')
if __name__=='__main__':main()
