"""Compile explicit initializer/second-startup/application-entry execution permission."""
import argparse,hashlib,json,re
from pathlib import Path
import crt_startup_policy as parent
from frame_target_policy import byte_array
from loader_policy import strict_object
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/application-entry-policy.json')
OUTPUT=Path('include/saex/engine/application_entry_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('application_policy_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=strict_object);crt=json.loads(parents[0]);profile=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])
    proxy=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/proxy-policy.json'))])
    keys={'schemaVersion','id','stage','crtPolicySha256','reviewDocument','initializerBodyHex','initializerReturnHex','secondCallRva','secondReturnHex','reentryRva','onceRva','reentryNormalizedHex'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('application_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or p['stage']!='before-application-body':raise ValueError('application_policy_stage')
    if not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']):raise ValueError('application_policy_id')
    if p['crtPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('application_policy_parent')
    if p['reviewDocument']!='docs/development/d1-application-entry.md':raise ValueError('application_policy_review')
    def hexdata(key,n=None):
        v=p[key]
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]+',v) or len(v)%2 or (n and len(v)!=n*2):raise ValueError('application_policy_hex')
        return bytes.fromhex(v)
    body=hexdata('initializerBodyHex');hexdata('initializerReturnHex',16);hexdata('secondReturnHex',16);prefix=hexdata('reentryNormalizedHex',31)
    if not 16<=len(body)<=256 or body[:16].hex()!=crt['initialize']['targetPrefixHex']:raise ValueError('application_policy_body')
    if type(p['secondCallRva']) is not int:raise ValueError('application_policy_call')
    spans=[(crt['io']['callRva'],21),(crt['io']['targetRva'],16),(crt['initialize']['callRva'],21),(crt['initialize']['targetRva'],len(body)),
        (crt['application']['callRva'],5),(crt['application']['targetRva'],16),(p['secondCallRva'],22)]
    for r,n in spans:
        if not 4096<=r<=profile['layout']['imageSize']-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&0x20000000 for s in profile['layout']['sections']):raise ValueError('application_policy_range')
    spans += [(t['rva'],len(t['targets'])*4) for t in crt['tables']]
    for i,(r,n) in enumerate(spans):
        if any(r<b+m and b<r+n for b,m in spans[:i]):raise ValueError('application_policy_overlap')
    if type(p['reentryRva']) is not int or p['reentryRva']!=proxy['iatTargetRva']:raise ValueError('application_policy_reentry')
    once=p['onceRva']
    if type(once) is not int or not 0<once<16*1024*1024 or p['reentryRva']<=once<p['reentryRva']+31:raise ValueError('application_policy_once')
    expected={0:0x55,1:0x8b,2:0xec,3:0x80,4:0x3d,9:0,10:0x75,11:0x0c,12:0xe8,17:0xc6,18:5,23:1,24:0x5d,25:0xff,26:0x25}
    if any(prefix[i]!=v for i,v in expected.items()) or any(prefix[at:at+4]!=b'\0'*4 for at in (5,19,27)):raise ValueError('application_policy_guard')
    target=p['reentryRva']+17+int.from_bytes(prefix[13:17],'little',signed=True)
    if not 0<target<16*1024*1024 or p['reentryRva']<=target<p['reentryRva']+31:raise ValueError('application_policy_reentry_call')
    return '\n'.join(['// Generated by tools/application_entry_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/application_entry.hpp"','#include "saex/engine/crt_startup_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_crt_policy_digest == "{p["crtPolicySha256"]}");',f'inline constexpr std::string_view reviewed_application_policy_id="{p["id"]}";',
        f'inline constexpr std::string_view reviewed_application_policy_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr std::array<std::byte,{len(body)}> reviewed_initializer_body'+byte_array(p['initializerBodyHex'])+';',
        'inline constexpr ApplicationEntrySpec reviewed_application_spec{reviewed_initializer_body,'+byte_array(p['initializerReturnHex'])+','+byte_array(p['secondReturnHex'])+','+
        ','.join(str(p[k])+'U' for k in ('secondCallRva','reentryRva','onceRva'))+','+byte_array(p['reentryNormalizedHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('application_policy_size')
    if not (ROOT/'docs/development/d1-application-entry.md').is_file():raise ValueError('application_policy_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_application_policy_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Application entry policy verified.' if args.check else 'Application entry policy generated.')
if __name__=='__main__':main()
