"""Compile a reviewed ASI call/return boundary; artifact identity is build-specific."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import binding_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/asi-policy.json')
OUTPUT = Path('include/saex/engine/asi_policy.generated.hpp')
SOURCES = (SOURCE, *binding_policy.SOURCES)


def compile_source(data, *parents):
    if max(map(len, (data, *parents))) > 65536: raise ValueError('asi_policy_size')
    binding_policy.compile_source(*parents)
    p = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion', 'id', 'stage', 'bindingPolicySha256', 'callRva', 'returnHex', 'endRva', 'endHex',
            'artifactName', 'reviewDocument', 'commonModules', 'debugModules'}
    if type(p) is not dict or set(p) != keys: raise ValueError('asi_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'single-asi-return-boundary':
        raise ValueError('asi_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', p['id']): raise ValueError('asi_policy_id')
    if p['bindingPolicySha256'] != hashlib.sha256(parents[0]).hexdigest(): raise ValueError('asi_policy_binding_drift')
    if p['reviewDocument'] != 'docs/development/d1-asi-bootstrap-load.md': raise ValueError('asi_policy_review')
    if p['artifactName'] != 'saex_bootstrap.asi': raise ValueError('asi_policy_artifact')
    for key in ['callRva', 'endRva']:
        if type(p[key]) is not int or not 0 < p[key] <= 256 * 1024 * 1024 - 22: raise ValueError('asi_policy_rva')
    if p['callRva'] <= p['endRva'] < p['callRva'] + 22: raise ValueError('asi_policy_rva')
    for key in ['returnHex', 'endHex']:
        if not isinstance(p[key], str) or not re.fullmatch(r'[0-9a-f]{32}', p[key]) or p[key] == '0'*32:
            raise ValueError('asi_policy_return_bytes')
    for key, names in [('commonModules', ('bcrypt.dll',)), ('debugModules', ('msvcp140d.dll', 'vcruntime140d.dll', 'ucrtbased.dll'))]:
        if type(p[key]) is not list or len(p[key]) != len(names): raise ValueError('asi_policy_closure')
        for m, name in zip(p[key], names):
            if type(m) is not dict or set(m) != {'name', 'bytes', 'sha256'} or m['name'] != name: raise ValueError('asi_policy_module')
            if type(m['bytes']) is not int or not 0 < m['bytes'] <= 64*1024*1024: raise ValueError('asi_policy_bytes')
            if not isinstance(m['sha256'], str) or not re.fullmatch(r'[0-9a-f]{64}', m['sha256']) or m['sha256'] == '0'*64:
                raise ValueError('asi_policy_hash')
    return_bytes = '{' + ', '.join('std::byte{0x'+p['returnHex'][i:i+2]+'}' for i in range(0,32,2)) + '}'
    end_bytes = '{' + ', '.join('std::byte{0x'+p['endHex'][i:i+2]+'}' for i in range(0,32,2)) + '}'
    lines = ['// Generated by tools/asi_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/binding_policy.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_binding_policy_digest == "{p["bindingPolicySha256"]}", "ASI binding drift");',
        f'inline constexpr std::string_view reviewed_asi_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_asi_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr std::string_view reviewed_asi_artifact_name = "saex_bootstrap.asi";',
        f'inline constexpr AsiStopSpec reviewed_asi_spec{{nullptr, {p["callRva"]}, {p["endRva"]}, {return_bytes}, {end_bytes}, {{}}}};']
    for key in ['commonModules', 'debugModules']:
        lines += [f'inline constexpr std::array<LoaderPinSpec, {len(p[key])}> reviewed_asi_{key}{{{{']
        for m in p[key]:
            lines += [f'    LoaderPinSpec{{LoaderOrigin::system_x86, "{m["name"]}", {m["bytes"]}ULL, {loader_policy.byte_array(m["sha256"])}}},']
        lines += ['}};']
    return '\n'.join(lines + ['}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT/p for p in SOURCES]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('asi_policy_size')
    if not (ROOT/'docs/development/d1-asi-bootstrap-load.md').is_file(): raise ValueError('asi_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8') != output: raise ValueError('stale_asi_policy_generated_output')
    else: (ROOT/OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed ASI return policy verified.' if args.check else 'Reviewed ASI return policy generated.')


if __name__ == '__main__': main()
