"""Compile reviewed direct codec bindings; never discover or invoke native exports."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import codec_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/binding-policy.json')
OUTPUT = Path('include/saex/engine/binding_policy.generated.hpp')
SOURCES = (SOURCE, *codec_policy.SOURCES)
NAMES = ('ov_open_callbacks', 'ov_clear', 'ov_time_total', 'ov_time_tell', 'ov_read', 'ov_info', 'ov_time_seek', 'ov_time_seek_page')


def compile_source(data, *parents):
    if max(map(len, (data, *parents))) > 65536: raise ValueError('binding_policy_size')
    codec_policy.compile_source(*parents)
    p = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion','id','stage','codecPolicySha256','stopRva','procSlotRva','stopHex','reviewDocument','bindings'}
    if type(p) is not dict or set(p) != keys: raise ValueError('binding_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'codec-bindings-boundary':
        raise ValueError('binding_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}',p['id']): raise ValueError('binding_policy_id')
    if p['codecPolicySha256'] != hashlib.sha256(parents[0]).hexdigest(): raise ValueError('binding_policy_codec_drift')
    if p['reviewDocument'] != 'docs/development/d1-codec-bindings.md': raise ValueError('binding_policy_review')
    def rva(value): return type(value) is int and 0 < value <= 256 * 1024 * 1024 - 16
    if not rva(p['stopRva']) or not rva(p['procSlotRva']) or p['procSlotRva'] % 4: raise ValueError('binding_policy_rva')
    if not isinstance(p['stopHex'],str) or not re.fullmatch(r'[0-9a-f]{32}',p['stopHex']) or p['stopHex']=='0'*32:
        raise ValueError('binding_policy_stop_bytes')
    if type(p['bindings']) is not list or len(p['bindings']) != 8: raise ValueError('binding_policy_count')
    slots = set()
    for b, name in zip(p['bindings'],NAMES):
        if type(b) is not dict or set(b) != {'name','slotRva','targetRva'} or b['name'] != name: raise ValueError('binding_policy_entry')
        if not rva(b['slotRva']) or b['slotRva'] % 4 or not rva(b['targetRva']): raise ValueError('binding_policy_rva')
        if b['slotRva'] in slots: raise ValueError('binding_policy_duplicate_slot')
        slots.add(b['slotRva'])
    stop = '{' + ', '.join('std::byte{0x'+p['stopHex'][i:i+2]+'}' for i in range(0,32,2)) + '}'
    lines = ['// Generated by tools/binding_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/codec_policy.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_codec_policy_digest == "{p["codecPolicySha256"]}", "binding codec drift");',
        f'inline constexpr std::string_view reviewed_binding_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_binding_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr std::array<BindingSlotSpec, 8> reviewed_binding_slots{{']
    for b in p['bindings']: lines.append(f'    BindingSlotSpec{{"{b["name"]}", {b["slotRva"]}, {b["targetRva"]}}},')
    return '\n'.join(lines+['}};',f'inline constexpr BindingStopSpec reviewed_binding_spec{{{p["stopRva"]}, {p["procSlotRva"]}, {stop}, reviewed_binding_slots}};', '}', ''])


def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths): raise ValueError('binding_policy_size')
    if not (ROOT/'docs/development/d1-codec-bindings.md').is_file(): raise ValueError('binding_policy_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8') != output: raise ValueError('stale_binding_policy_generated_output')
    else: (ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Reviewed codec bindings policy verified.' if args.check else 'Reviewed codec bindings policy generated.')


if __name__=='__main__': main()
