"""Explicit fixed bootstrap lifecycle permission, chained to the ASI recipe."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import asi_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/bootstrap-lifecycle-policy.json')
OUTPUT = Path('include/saex/engine/bootstrap_lifecycle_policy.generated.hpp')
SOURCES = (SOURCE, *asi_policy.SOURCES)


def compile_source(data, *parents):
    if max(map(len, (data, *parents))) > 65536: raise ValueError('bootstrap_policy_size')
    asi_policy.compile_source(*parents)
    p = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p) != {'schemaVersion', 'id', 'stage', 'asiPolicySha256', 'reviewDocument', 'callSequence', 'cryptoModule'}:
        raise ValueError('bootstrap_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'owned-main-thread-bootstrap-lifecycle':
        raise ValueError('bootstrap_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', p['id']): raise ValueError('bootstrap_policy_id')
    if p['asiPolicySha256'] != hashlib.sha256(parents[0]).hexdigest(): raise ValueError('bootstrap_policy_parent_drift')
    if p['reviewDocument'] != 'docs/development/d1-bootstrap-lifecycle.md': raise ValueError('bootstrap_policy_review')
    if p['callSequence'] != ['Query', 'Initialize', 'Query', 'Initialize', 'Stop', 'Query', 'Initialize', 'Stop']:
        raise ValueError('bootstrap_policy_sequence')
    m = p['cryptoModule']
    if type(m) is not dict or set(m) != {'name', 'bytes', 'sha256'} or m['name'] != 'bcryptprimitives.dll': raise ValueError('bootstrap_policy_module')
    if type(m['bytes']) is not int or not 0 < m['bytes'] <= 64*1024*1024: raise ValueError('bootstrap_policy_bytes')
    if not isinstance(m['sha256'], str) or not re.fullmatch(r'[0-9a-f]{64}', m['sha256']) or m['sha256'] == '0'*64:
        raise ValueError('bootstrap_policy_hash')
    return '\n'.join(['// Generated by tools/bootstrap_lifecycle_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/asi_policy.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_asi_policy_digest == "{p["asiPolicySha256"]}", "Bootstrap ASI drift");',
        'static_assert(bootstrap_call_sequence == std::array<std::uint32_t,8>{1,0,1,0,2,1,0,2});',
        f'inline constexpr std::string_view reviewed_bootstrap_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_bootstrap_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr LoaderPinSpec reviewed_bootstrap_crypto_pin{{LoaderOrigin::system_x86, "{m["name"]}", {m["bytes"]}ULL, {loader_policy.byte_array(m["sha256"])}}};',
        '}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT/p for p in SOURCES]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('bootstrap_policy_size')
    if not (ROOT/'docs/development/d1-bootstrap-lifecycle.md').is_file(): raise ValueError('bootstrap_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8') != output: raise ValueError('stale_bootstrap_policy_output')
    else: (ROOT/OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed bootstrap lifecycle policy verified.' if args.check else 'Reviewed bootstrap lifecycle policy generated.')


if __name__ == '__main__': main()
