"""Compile the explicit disk-query and allocation-argument observation permission."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cd_stream_tables_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cd-stream-disk-policy.json')
OUTPUT=Path('include/saex/engine/cd_stream_disk_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cd_stream_disk_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','tablesPolicySha256','reviewDocument','flagsRva','allocatorRva','thunkSlotRva','bodyHex','function','implementation','systemModules'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cd_stream_disk_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-aligned-allocation':raise ValueError('cd_stream_disk_identity')
    if p['tablesPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cd_stream_disk_parent')
    if p['reviewDocument']!='docs/development/d1-cd-stream-disk.md':raise ValueError('cd_stream_disk_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];base=layout['imageBase'];size=layout['imageSize']
    t=json.loads(parents[0]);m=src('contracts/engine/file-manager-entry-policy.json')
    flags,alloc,slot=(p[k] for k in ('flagsRva','allocatorRva','thunkSlotRva'))
    if any(type(v) is not int or not 4100<=v<16*1024*1024-137 for v in (flags,alloc,slot)) or flags%4 or slot%4:raise ValueError('cd_stream_disk_range')
    spans=[(t['targetRva'],137,0x20000000),(flags-4,20,0xc0000000),(alloc,1,0x20000000),(t['handlesRva']-4,2192,0xc0000000),(m['bufferRva']-4,136,0xc0000000),(t['diskIatRva'],4,0x40000000)]
    for i,(r,length,mask) in enumerate(spans):
        if not any(s['rva']<=r and r+length<=s['rva']+(s['virtualSize'] if mask==0xc0000000 else s['rawSize']) and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cd_stream_disk_section')
        if any(r<a+b and a<r+length for a,b,_ in spans[:i]):raise ValueError('cd_stream_disk_overlap')
    u32=lambda v:struct.pack('<I',v&0xffffffff)
    body=b'\xff\x15'+u32(base+t['diskIatRva'])+bytes.fromhex('8b4c240433c081f9000800007705b800000020566a00510d000000406800080000c705')+u32(base+flags+8)+bytes.fromhex('01000000a3')+u32(base+flags)+bytes.fromhex('c705')+u32(base+flags+4)+bytes.fromhex('00000000e8')+u32(alloc-t['targetRva']-137)
    if p['bodyHex']!=body.hex():raise ValueError('cd_stream_disk_body')
    modules=p['systemModules'];known=src('contracts/engine/loader-policy.json')['modules']
    if type(modules) is not list or len(modules)!=2:raise ValueError('cd_stream_disk_modules')
    for v,name in zip(modules,('kernel32.dll','kernelbase.dll')):
        expected=next(x for x in known if x['name']==name)
        if type(v) is not dict or set(v)!={'name','bytes','sha256'} or type(v['bytes']) is not int or v!={k:expected[k] for k in v}:raise ValueError('cd_stream_disk_module')
    for key,length in [('function',6),('implementation',20)]:
        a=p[key]
        if type(a) is not dict or set(a)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('cd_stream_disk_function')
        if type(a['rva']) is not int or not 4096<=a['rva']<16*1024*1024-length or type(a['preferredBase']) is not int or not 0<a['preferredBase']<=0xffff0000 or a['preferredBase']%65536:raise ValueError('cd_stream_disk_function_range')
        if not isinstance(a['prefixHex'],str) or not re.fullmatch('[0-9a-f]{'+str(length*2)+'}',a['prefixHex']):raise ValueError('cd_stream_disk_prefix')
        offsets=a['highlowOffsets']
        if type(offsets) is not list or any(type(x) is not int or not 0<=x<=length-4 for x in offsets) or sorted(offsets)!=offsets or any(b-a<4 for a,b in zip(offsets,offsets[1:])):raise ValueError('cd_stream_disk_fixups')
    f=p['function'];a=p['implementation']
    if f['preferredBase']+slot>0xffffffff or f['highlowOffsets']!=[2] or f['prefixHex']!='ff25'+u32(f['preferredBase']+slot).hex() or f['rva']<slot+4 and slot<f['rva']+6:raise ValueError('cd_stream_disk_thunk')
    spec=f'BootstrapExportSpec{{{a["rva"]}U,'+byte_array(a['prefixHex'])+f',{a["preferredBase"]}U,{sum(1<<x for x in a["highlowOffsets"])}U'+'}'
    return '\n'.join(['// Generated by tools/cd_stream_disk_policy.py. Do not edit.','#pragma once','#include "saex/engine/cd_stream_disk.hpp"','#include "saex/engine/cd_stream_tables_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cd_stream_tables_digest=="{p["tablesPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cd_stream_disk_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cd_stream_disk_digest="{hashlib.sha256(data).hexdigest()}";',f'inline constexpr CdStreamDiskSpec reviewed_cd_stream_disk_spec{{{flags}U,{alloc}U,{f["rva"]}U,{slot}U,'+spec+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cd_stream_disk_size')
    result=compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=result:raise ValueError('stale_cd_stream_disk_output')
    else:(ROOT/OUTPUT).write_text(result,encoding='utf-8',newline='\n')
    print('CdStream disk policy verified.' if args.check else 'CdStream disk policy generated.')
if __name__=='__main__':main()
