"""Compile the bounded CdStream table permission; Ghidra exports never grant access."""
import argparse, hashlib, json, re, struct
from pathlib import Path
import file_manager_ready_policy as parent
import loader_policy
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cd-stream-tables-policy.json')
OUTPUT=Path('include/saex/engine/cd_stream_tables_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cd_stream_tables_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','readyPolicySha256','reviewDocument','targetRva','handlesRva','namesRva','diskIatRva','bodyHex','diskImport'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cd_stream_tables_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-disk-query-call':raise ValueError('cd_stream_tables_identity')
    if p['readyPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cd_stream_tables_parent')
    if p['reviewDocument']!='docs/development/d1-cd-stream-tables.md' or p['diskImport']!='GetDiskFreeSpaceA':raise ValueError('cd_stream_tables_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];base=layout['imageBase'];size=layout['imageSize']
    m=src('contracts/engine/file-manager-entry-policy.json');caller=m['manager']['callRva']+5
    t,h,n,iat=(p[k] for k in ('targetRva','handlesRva','namesRva','diskIatRva'))
    if any(type(v) is not int or not 4100<=v<size for v in (t,h,n,iat)) or h%4 or iat%4 or n!=h+136:raise ValueError('cd_stream_tables_range')
    spans=[(t,74,0x20000000),(h-4,2192,0xc0000000),(iat,4,0x40000000),(caller,7,0x20000000),(m['bufferRva']-4,136,0xc0000000)]
    for i,(r,length,mask) in enumerate(spans):
        if not any(s['rva']<=r and r+length<=s['rva']+(s['virtualSize'] if mask==0xc0000000 else s['rawSize']) and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cd_stream_tables_section')
        if any(r<a+b and a<r+length for a,b,_ in spans[:i]):raise ValueError('cd_stream_tables_overlap')
    u32=lambda v:struct.pack('<I',v&0xffffffff)
    call=b'\x6a\x05\xe8'+u32(t-caller-7)
    if not bytes.fromhex(m['returnPrefixHex']).startswith(call):raise ValueError('cd_stream_tables_caller')
    body=bytes.fromhex('83ec1057b92000000033c0bf')+u32(base+h)+b'\xba'+u32(base+n)+bytes.fromhex('f3abeb078da42400000000c6020083c24081fa')+u32(base+n+2048)+bytes.fromhex('7cf28d442408508d4c2410518d54240c528d44241c506a00ff15')+u32(base+iat)
    if p['bodyHex']!=body.hex():raise ValueError('cd_stream_tables_body')
    return '\n'.join(['// Generated by tools/cd_stream_tables_policy.py. Do not edit.','#pragma once','#include "saex/engine/cd_stream_tables.hpp"','#include "saex/engine/file_manager_ready_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_file_manager_ready_digest=="{p["readyPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cd_stream_tables_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cd_stream_tables_digest="{hashlib.sha256(data).hexdigest()}";',f'inline constexpr CdStreamTablesSpec reviewed_cd_stream_tables_spec{{{t}U,{h}U,{n}U,{iat}U}};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cd_stream_tables_size')
    out=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=out:raise ValueError('stale_cd_stream_tables_output')
    else:(ROOT/OUTPUT).write_text(out,encoding='utf-8',newline='\n')
    print('CdStream tables policy verified.' if a.check else 'CdStream tables policy generated.')
if __name__=='__main__':main()
