"""Compile one reviewed dynamic codec return boundary; no runtime discovery."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import startup_policy
import proxy_policy
import entry_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/codec-policy.json')
OUTPUT = Path('include/saex/engine/codec_policy.generated.hpp')
SOURCES = (SOURCE, startup_policy.SOURCE, proxy_policy.SOURCE, entry_policy.SOURCE,
           loader_policy.SOURCE, startup_policy.PROFILE)


def compile_source(data, startup, proxy, entry, base, observed):
    if max(map(len, (data, startup, proxy, entry, base, observed))) > 65536: raise ValueError('codec_policy_size')
    startup_policy.compile_source(startup, proxy, entry, base, observed)
    p = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion', 'id', 'stage', 'startupPolicySha256', 'sequenceRva', 'nameRva',
            'loadSlotRva', 'requestedName', 'callForm', 'reviewDocument', 'modules'}
    if type(p) is not dict or set(p) != keys: raise ValueError('codec_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'codec-return-boundary':
        raise ValueError('codec_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', p['id']): raise ValueError('codec_policy_id')
    if p['startupPolicySha256'] != hashlib.sha256(startup).hexdigest(): raise ValueError('codec_policy_startup_drift')
    if p['callForm'] != 'x86-push-ff15-mov-edi-eax': raise ValueError('codec_policy_call_form')
    if p['reviewDocument'] != 'docs/development/d1-codec-return.md': raise ValueError('codec_policy_review')
    for key in ('sequenceRva', 'nameRva', 'loadSlotRva'):
        if type(p[key]) is not int or not 0 < p[key] <= 256 * 1024 * 1024 - 16: raise ValueError('codec_policy_rva')
    if p['loadSlotRva'] % 4: raise ValueError('codec_policy_alignment')
    # This recipe admits only the reviewed three-file closure; changing its scope needs a new compiler review.
    if p['requestedName'] != 'vorbishooked' or type(p['modules']) is not list or len(p['modules']) != 3:
        raise ValueError('codec_policy_closure')
    expected = ('vorbishooked.dll', 'vorbis.dll', 'ogg.dll')
    for m, name in zip(p['modules'], expected):
        if type(m) is not dict or set(m) != {'name', 'bytes', 'sha256'} or m['name'] != name:
            raise ValueError('codec_policy_module')
        if type(m['bytes']) is not int or not 0 < m['bytes'] <= 64 * 1024 * 1024: raise ValueError('codec_policy_bytes')
        if not isinstance(m['sha256'], str) or not re.fullmatch(r'[0-9a-f]{64}', m['sha256']) or m['sha256'] == '0' * 64:
            raise ValueError('codec_policy_hash')
    old = json.loads(base)['modules'] + json.loads(entry)['additionalModules']
    if set(expected) & {m['name'] for m in old}: raise ValueError('codec_policy_override')
    if sum(m['bytes'] for m in old + p['modules']) > 256 * 1024 * 1024: raise ValueError('codec_policy_total')
    lines = ['// Generated by tools/codec_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/startup_policy.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_startup_policy_digest == "{p["startupPolicySha256"]}", "codec startup drift");',
        f'inline constexpr std::string_view reviewed_codec_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_codec_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr std::array<std::string_view, 3> reviewed_codec_modules{"vorbishooked.dll", "vorbis.dll", "ogg.dll"};',
        'inline constexpr auto reviewed_codec_specs = [] {',
        '    std::array<LoaderPinSpec, reviewed_entry_specs.size() + 3> result{};',
        '    for (std::size_t i = 0; i < reviewed_entry_specs.size(); ++i) result[i] = reviewed_entry_specs[i];']
    for i, m in enumerate(p['modules']):
        lines.append(f'    result[reviewed_entry_specs.size() + {i}] = LoaderPinSpec{{LoaderOrigin::game_root, "{m["name"]}", {m["bytes"]}ULL, {loader_policy.byte_array(m["sha256"])}}};')
    return '\n'.join(lines + ['    return result;', '}();',
        f'inline constexpr CodecStopSpec reviewed_codec_spec{{{p["sequenceRva"]}, {p["nameRva"]}, {p["loadSlotRva"]}, "{p["requestedName"]}", {{}}}};', '}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT / p for p in SOURCES]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('codec_policy_size')
    if not (ROOT / 'docs/development/d1-codec-return.md').is_file(): raise ValueError('codec_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT / OUTPUT).is_file() or (ROOT / OUTPUT).read_text(encoding='utf-8') != output:
            raise ValueError('stale_codec_policy_generated_output')
    else: (ROOT / OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed codec-return policy verified.' if args.check else 'Reviewed codec-return policy generated.')


if __name__ == '__main__': main()
