"""Compile a bounded CRT initializer barrier; never authorize initializer execution."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import startup_return_policy as parent
import loader_policy
from frame_target_policy import byte_array

ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/crt-startup-policy.json')
OUTPUT=Path('include/saex/engine/crt_startup_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536: raise ValueError('crt_policy_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    profile=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])
    layout=profile['layout']; base=layout['imageBase']; size=layout['imageSize']
    keys={'schemaVersion','id','stage','startupReturnPolicySha256','reviewDocument','io','initialize','application','ioReturnHex','ioReturnStackOffset','tables'}
    if type(p) is not dict or set(p)!=keys: raise ValueError('crt_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or p['stage']!='before-crt-initializers': raise ValueError('crt_policy_stage')
    if not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']): raise ValueError('crt_policy_id')
    if p['startupReturnPolicySha256']!=hashlib.sha256(parents[0]).hexdigest(): raise ValueError('crt_policy_parent')
    if p['reviewDocument']!='docs/development/d1-crt-startup.md': raise ValueError('crt_policy_review')
    def hex_bytes(value,length):
        if not isinstance(value,str) or not re.fullmatch('[0-9a-f]{'+str(length*2)+'}',value): raise ValueError('crt_policy_hex')
        return bytes.fromhex(value)
    spans=[]
    def span(r,length,code=False):
        if type(r) is not int or not 4096<=r<=size-length: raise ValueError('crt_policy_range')
        if not any(s['rva']<=r and r+length<=s['rva']+s['rawSize'] and (not code or s['characteristics']&0x20000000) for s in layout['sections']): raise ValueError('crt_policy_section')
    frames=[]
    for key in ('io','initialize','application'):
        f=p[key]
        if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}: raise ValueError('crt_policy_call_keys')
        call=hex_bytes(f['callHex'],5); hex_bytes(f['targetPrefixHex'],16)
        length=21 if key=='io' else 5
        span(f['callRva'],length,True); span(f['targetRva'],16,True)
        spans.extend([(f['callRva'],length),(f['targetRva'],16)])
        if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']: raise ValueError('crt_policy_rel32')
        frames.append(f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,{byte_array(f["callHex"])},{byte_array(f["targetPrefixHex"])}}}')
    hex_bytes(p['ioReturnHex'],16)
    offset=p['ioReturnStackOffset']
    if type(offset) is not int or not 16<=offset<=4096 or offset%4: raise ValueError('crt_policy_stack')
    if type(p['tables']) is not list or len(p['tables'])!=3: raise ValueError('crt_policy_tables')
    total=0; arrays=[]; tables=[]
    for i,(table,name) in enumerate(zip(p['tables'],('floating-point-hook','c-initializers','cpp-initializers'))):
        if type(table) is not dict or set(table)!={'name','rva','targets'} or table['name']!=name: raise ValueError('crt_policy_table_keys')
        targets=table['targets']
        if type(targets) is not list or not targets: raise ValueError('crt_policy_targets')
        total+=len(targets)
        if total>2048: raise ValueError('crt_policy_budget')
        span(table['rva'],len(targets)*4)
        if table['rva']%4: raise ValueError('crt_policy_alignment')
        spans.append((table['rva'],len(targets)*4))
        for target in targets:
            if type(target) is not int: raise ValueError('crt_policy_target_type')
            if target: span(target,1,True)
        arrays.append(f'inline constexpr std::array<std::uint32_t,{len(targets)}> reviewed_crt_targets_{i}{{'+','.join(str(v)+'U' for v in targets)+'};')
        tables.append(f'CrtInitializerTable{{{table["rva"]}U,reviewed_crt_targets_{i}}}')
    for i,(r,length) in enumerate(spans):
        if any(r<o+n and o<r+length for o,n in spans[:i]): raise ValueError('crt_policy_overlap')
    return '\n'.join(['// Generated by tools/crt_startup_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/crt_startup.hpp"','#include "saex/engine/startup_return_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_startup_return_digest == "{p["startupReturnPolicySha256"]}");',
        f'inline constexpr std::string_view reviewed_crt_policy_id="{p["id"]}";',
        f'inline constexpr std::string_view reviewed_crt_policy_digest="{hashlib.sha256(data).hexdigest()}";',
        *arrays,'inline constexpr std::array reviewed_crt_tables{'+','.join(tables)+'};',
        'inline constexpr CrtStartupSpec reviewed_crt_spec{'+','.join(frames)+','+byte_array(p['ioReturnHex'])+f',{offset}U,reviewed_crt_tables'+'};','}',''])

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths): raise ValueError('crt_policy_size')
    if not (ROOT/'docs/development/d1-crt-startup.md').is_file(): raise ValueError('crt_policy_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output: raise ValueError('stale_crt_policy_output')
    else: (ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('CRT initializer boundary policy verified.' if args.check else 'CRT initializer boundary policy generated.')
if __name__=='__main__': main()
