"""Compile reviewed cwd helper-return permission; no code discovery or execution."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_copy_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-return-policy.json')
OUTPUT=Path('include/saex/engine/cwd_return_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_return_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','copyPolicySha256','reviewDocument','checkerRva','cleanupHex','epilogueHex','checkerHex','returnPrefixHex'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cwd_return_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-helper-return-before-wrapper-cleanup':raise ValueError('cwd_return_identity')
    if p['copyPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_return_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-return.md':raise ValueError('cwd_return_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];q=src('contracts/engine/cwd-query-policy.json');lock=src('contracts/engine/cwd-lock-policy.json');copy=json.loads(parents[0])
    def region(r,n):
        if type(r) is not int or not 4096<=r<=layout['imageSize']-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&0x20000000 for s in layout['sections']):raise ValueError('cwd_return_range')
    region(p['checkerRva'],9);region(lock['selector']['callRva']+23,16)
    spans=[(q['helperRva'],247),(copy['copierRva'],248),(lock['selector']['callRva'],39),(q['cookieRva'],4),(q['iatRva'],4),(lock['tableRva']+52,16),(p['checkerRva'],9)]
    for i,(r,n) in enumerate(spans):
        if any(r<b+m and b<r+n for b,m in spans[:i]):raise ValueError('cwd_return_overlap')
    cleanup='5959e951ffffff'
    epilogue=(bytes.fromhex('8b4dfc334d045be8')+struct.pack('<I',(p['checkerRva']-q['helperRva']-75)&0xffffffff)+bytes.fromhex('c9c3')).hex()
    checker=(bytes.fromhex('3b0d')+struct.pack('<I',layout['imageBase']+q['cookieRva'])+bytes.fromhex('7501c3')).hex()
    for k,v in [('cleanupHex',cleanup),('epilogueHex',epilogue),('checkerHex',checker)]:
        if p[k]!=v:raise ValueError('cwd_return_body')
    if copy['returnPrefixHex'][:14]!=cleanup:raise ValueError('cwd_return_copy_chain')
    if not isinstance(p['returnPrefixHex'],str) or not re.fullmatch('[0-9a-f]{32}',p['returnPrefixHex']):raise ValueError('cwd_return_prefix')
    return '\n'.join(['// Generated by tools/cwd_return_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_return.hpp"','#include "saex/engine/cwd_copy_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_copy_digest == "{p["copyPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_return_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_return_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr CwdReturnSpec reviewed_cwd_return_spec{{{p["checkerRva"]}U,'+byte_array(p['returnPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_return_size')
    if not (ROOT/'docs/development/d1-cwd-return.md').is_file():raise ValueError('cwd_return_review_missing')
    result=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=result:raise ValueError('stale_cwd_return_output')
    else:(ROOT/OUTPUT).write_text(result,encoding='utf-8',newline='\n')
    print('Cwd return policy verified.' if a.check else 'Cwd return policy generated.')
if __name__=='__main__':main()
