"""Reviewed drive-zero cwd query. Generates metadata only; never executes code."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_acquire_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-query-policy.json')
OUTPUT=Path('include/saex/engine/cwd_query_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_query_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','acquirePolicySha256','reviewDocument','helperRva','cookieRva','iatRva','thunkSlotRva','wrapperHex','helperHex','queryHex','returnPrefixHex','function','implementation','systemModules'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cwd_query_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-get-current-directory-before-copy':raise ValueError('cwd_query_identity')
    if p['acquirePolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_query_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-query.md':raise ValueError('cwd_query_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];base=layout['imageBase'];size=layout['imageSize']
    lock=src('contracts/engine/cwd-lock-policy.json');call=lock['selector']['callRva']
    def region(r,n,code=True):
        mask=0x20000000 if code else 0x40000000
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cwd_query_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(2*n)+'}',v):raise ValueError('cwd_query_hex')
        return bytes.fromhex(v)
    region(p['helperRva'],157);region(call,23)
    for k in ('iatRva','cookieRva'):
        region(p[k],4,False)
        if p[k]%4:raise ValueError('cwd_query_alignment')
    spans=[(call,23),(p['helperRva'],157),(p['cookieRva'],4),(p['iatRva'],4),(lock['tableRva']+52,16)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+c and q<r+n for q,c in spans[:i]):raise ValueError('cwd_query_overlap')
    w=bytes.fromhex('598365fc00ff750cff75086a00e8')+struct.pack('<I',(p['helperRva']-call-23)&0xffffffff)
    h=bytes.fromhex('558bec81ec0c010000a1')+struct.pack('<I',base+p['cookieRva'])+bytes.fromhex('334504538b5d0885db8945fc745f')
    q=bytes.fromhex('8d85f4feffff506804010000ff15')+struct.pack('<I',base+p['iatRva'])
    for key,value in [('wrapperHex',w),('helperHex',h),('queryHex',q)]:
        if hx(p[key],len(value))!=value:raise ValueError('cwd_query_body')
    if w[:16]!=bytes.fromhex(json.loads(parents[0])['returnPrefixHex']):raise ValueError('cwd_query_return_chain')
    hx(p['returnPrefixHex'],16)
    modules=p['systemModules'];known=src('contracts/engine/loader-policy.json')['modules']
    if type(modules) is not list or len(modules)!=2:raise ValueError('cwd_query_modules')
    for m,name in zip(modules,('kernel32.dll','kernelbase.dll')):
        expected=next(x for x in known if x['name']==name)
        if type(m) is not dict or set(m)!={'name','bytes','sha256'} or type(m['bytes']) is not int or m!={k:expected[k] for k in m}:raise ValueError('cwd_query_module')
    specs=[]
    for key in ('function','implementation'):
        a=p[key]
        if type(a) is not dict or set(a)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('cwd_query_function')
        if type(a['rva']) is not int or not 4096<=a['rva']<16*1024*1024-20 or type(a['preferredBase']) is not int or not 0<a['preferredBase']<=0xffff0000 or a['preferredBase']%65536:raise ValueError('cwd_query_function_range')
        hx(a['prefixHex'],20);offsets=a['highlowOffsets']
        if type(offsets) is not list or any(type(x) is not int or not 0<=x<=16 for x in offsets) or sorted(offsets)!=offsets or any(b-a<4 for a,b in zip(offsets,offsets[1:])):raise ValueError('cwd_query_fixups')
        specs.append(f'BootstrapExportSpec{{{a["rva"]}U,'+byte_array(a['prefixHex'])+f',{a["preferredBase"]}U,{sum(1<<x for x in offsets)}U'+'}')
    slot=p['thunkSlotRva'];a=p['function']
    if type(slot) is not int or not 4096<=slot<16*1024*1024-4 or slot%4 or a['preferredBase']+slot>0xffffffff:raise ValueError('cwd_query_thunk')
    if a['highlowOffsets']!=[8] or bytes.fromhex(a['prefixHex'])[:12]!=bytes.fromhex('8bff558bec5dff25')+struct.pack('<I',a['preferredBase']+slot):raise ValueError('cwd_query_thunk_body')
    return '\n'.join(['// Generated by tools/cwd_query_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_query.hpp"','#include "saex/engine/cwd_acquire_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_acquire_digest == "{p["acquirePolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_query_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_query_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr CwdQuerySpec reviewed_cwd_query_spec{{{p["helperRva"]}U,{p["cookieRva"]}U,{p["iatRva"]}U,{slot}U,'+','.join(specs)+','+byte_array(p['returnPrefixHex'])+'};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_query_size')
    if not (ROOT/'docs/development/d1-cwd-query.md').is_file():raise ValueError('cwd_query_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_cwd_query_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Cwd query policy verified.' if a.check else 'Cwd query policy generated.')
if __name__=='__main__':main()
