"""Pin the existing-slot CRT path and the admitted x86 Windows API entry."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_lock_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-acquire-policy.json')
OUTPUT=Path('include/saex/engine/cwd_acquire_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_acquire_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','lockPolicySha256','reviewDocument','iatRva','bodyHex','returnPrefixHex','function','systemModule'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cwd_acquire_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-enter-and-selector-return':raise ValueError('cwd_acquire_identity')
    if p['lockPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_acquire_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-acquire.md':raise ValueError('cwd_acquire_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];base=layout['imageBase'];size=layout['imageSize'];m=json.loads(parents[0]);f=m['selector']
    def region(r,n,code=True):
        mask=0x20000000 if code else 0x40000000
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cwd_acquire_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(2*n)+'}',v):raise ValueError('cwd_acquire_hex')
        return bytes.fromhex(v)
    region(p['iatRva'],4,False);region(f['targetRva'],49);region(f['callRva']+5,16)
    if p['iatRva']%4:raise ValueError('cwd_acquire_alignment')
    body=bytes.fromhex('ff36ff15')+struct.pack('<I',base+p['iatRva'])+bytes.fromhex('5e5dc3')
    if hx(p['bodyHex'],11)!=body or bytes.fromhex(m['stopPrefixHex'])[:2]!=bytes.fromhex('7513'):raise ValueError('cwd_acquire_body')
    ret=hx(p['returnPrefixHex'],16)
    seh=src('contracts/engine/cwd-seh-policy.json')
    if ret[:9]!=bytes.fromhex(seh['stopPrefixHex'])[7:]:raise ValueError('cwd_acquire_return_chain')
    spans=[(f['targetRva'],49),(f['callRva'],21),(m['tableRva']+52,16),(p['iatRva'],4)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+c and q<r+n for q,c in spans[:i]):raise ValueError('cwd_acquire_overlap')
    module=p['systemModule'];expected=next(m for m in src('contracts/engine/loader-policy.json')['modules'] if m['name']=='ntdll.dll')
    if type(module) is not dict or set(module)!={'name','bytes','sha256'} or type(module['bytes']) is not int or module!={k:expected[k] for k in module}:raise ValueError('cwd_acquire_module')
    a=p['function']
    if type(a) is not dict or set(a)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('cwd_acquire_function')
    if type(a['rva']) is not int or not 4096<=a['rva']<16*1024*1024-20 or type(a['preferredBase']) is not int or not 0<a['preferredBase']<=0xffff0000 or a['preferredBase']%65536 or a['highlowOffsets']!=[]:raise ValueError('cwd_acquire_function_range')
    hx(a['prefixHex'],20)
    return '\n'.join(['// Generated by tools/cwd_acquire_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_acquire.hpp"','#include "saex/engine/cwd_lock_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_lock_digest == "{p["lockPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_acquire_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_acquire_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr CwdAcquireSpec reviewed_cwd_acquire_spec{{{p["iatRva"]}U,BootstrapExportSpec{{{a["rva"]}U,'+byte_array(a['prefixHex'])+f',{a["preferredBase"]}U,0U'+'},'+byte_array(p['returnPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_acquire_size')
    if not (ROOT/'docs/development/d1-cwd-acquire.md').is_file():raise ValueError('cwd_acquire_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_cwd_acquire_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Cwd acquire policy verified.' if a.check else 'Cwd acquire policy generated.')
if __name__=='__main__':main()
