"""Pin the CRT cwd SEH prologue, not the lock or directory API call tree."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import file_manager_entry_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-seh-policy.json')
OUTPUT=Path('include/saex/engine/cwd_seh_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
BODY=bytes.fromhex('680000000064a100000000508b442410896c24108d6c24102be05356578b45f88965e8508b45fcc745fcffffffff8945f88d45f064a300000000c3')
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_seh_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p)!={'schemaVersion','id','stage','managerPolicySha256','reviewDocument','wrapper','prologue','scopeRva','handlerRva','cleanupRva','prologueBodyHex','scopeHex','stopPrefixHex'}:raise ValueError('cwd_seh_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-seh-before-lock':raise ValueError('cwd_seh_identity')
    if p['managerPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_seh_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-seh.md':raise ValueError('cwd_seh_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout'];base=layout['imageBase'];size=layout['imageSize'];m=json.loads(parents[0])
    def region(r,n,code=True):
        mask=0x20000000 if code else 0x40000000
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cwd_seh_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(2*n)+'}',v):raise ValueError('cwd_seh_hex')
        return bytes.fromhex(v)
    frames=[]
    for key in ('wrapper','prologue'):
        f=p[key]
        if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('cwd_seh_frame')
        region(f['callRva'],5);region(f['targetRva'],28 if key=='wrapper' else 59)
        call=hx(f['callHex'],5);hx(f['targetPrefixHex'],16)
        if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']:raise ValueError('cwd_seh_call')
        frames.append(f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,'+byte_array(f['callHex'])+','+byte_array(f['targetPrefixHex'])+'}')
    region(p['scopeRva'],12,False);region(p['handlerRva'],16);region(p['cleanupRva'],16)
    f,h=p['wrapper'],p['prologue'];stop=hx(p['stopPrefixHex'],16)
    if f['callRva']!=m['manager']['targetRva']+11 or f['targetRva']!=m['cwdRva'] or f['callHex']!=m['manager']['targetPrefixHex'][22:] or h['callRva']!=f['targetRva']+7:raise ValueError('cwd_seh_chain')
    addr=lambda value:struct.pack('<I',base+value)
    wrapper=b'\x6a\x0c\x68'+addr(p['scopeRva'])+bytes.fromhex(h['callHex'])+stop[:4]
    body=bytearray(BODY);body[1:5]=addr(p['handlerRva']);scope=bytes.fromhex('ffffffff00000000')+addr(p['cleanupRva'])
    if bytes.fromhex(f['targetPrefixHex'])!=wrapper or bytes.fromhex(h['targetPrefixHex'])!=body[:16] or hx(p['prologueBodyHex'],59)!=body or hx(p['scopeHex'],12)!=scope:raise ValueError('cwd_seh_body')
    spans=[(m['manager']['callRva'],21),(m['manager']['targetRva'],51),(m['bufferRva']-4,136),(m['suffixRva'],2),
        (f['targetRva'],28),(h['targetRva'],59),(p['scopeRva'],12),(p['handlerRva'],16),(p['cleanupRva'],16)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+c and q<r+n for q,c in spans[:i]):raise ValueError('cwd_seh_overlap')
    return '\n'.join(['// Generated by tools/cwd_seh_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_seh.hpp"','#include "saex/engine/file_manager_entry_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_file_manager_digest == "{p["managerPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_seh_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_seh_digest="{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr CwdSehSpec reviewed_cwd_seh_spec{'+','.join(frames)+f',{p["scopeRva"]}U,{p["handlerRva"]}U,{p["cleanupRva"]}U,'+byte_array(p['stopPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_seh_size')
    if not (ROOT/'docs/development/d1-cwd-seh.md').is_file():raise ValueError('cwd_seh_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_cwd_seh_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Cwd SEH policy verified.' if a.check else 'Cwd SEH policy generated.')
if __name__=='__main__':main()
