"""Pin lock(7) selection through CMP; stop before JNE and either lock path."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_seh_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-lock-policy.json')
OUTPUT=Path('include/saex/engine/cwd_lock_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_lock_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p)!={'schemaVersion','id','stage','sehPolicySha256','reviewDocument','selector','tableRva','bodyHex','stopPrefixHex'}:raise ValueError('cwd_lock_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-comparison-before-branch':raise ValueError('cwd_lock_identity')
    if p['sehPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_lock_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-lock.md':raise ValueError('cwd_lock_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout'];base=layout['imageBase'];size=layout['imageSize'];m=json.loads(parents[0])
    def region(r,n,code=True):
        mask=0x20000000 if code else 0xc0000000
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+(s['rawSize'] if code else s['virtualSize']) and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('cwd_lock_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(2*n)+'}',v):raise ValueError('cwd_lock_hex')
        return bytes.fromhex(v)
    f=p['selector']
    if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('cwd_lock_frame')
    region(f['callRva'],5);region(f['targetRva'],33);region(p['tableRva'],68,False)
    if p['tableRva']%4:raise ValueError('cwd_lock_alignment')
    call=hx(f['callHex'],5);prefix=hx(f['targetPrefixHex'],16);stop=hx(p['stopPrefixHex'],16)
    if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']:raise ValueError('cwd_lock_call')
    if f['callRva']!=m['prologue']['callRva']+7 or bytes.fromhex(m['stopPrefixHex'])[:7]!=b'\x6a\x07'+call:raise ValueError('cwd_lock_chain')
    body=bytes.fromhex('558bec8b4508568d34c5')+struct.pack('<I',base+p['tableRva'])+bytes.fromhex('833e00')
    if hx(p['bodyHex'],17)!=body or prefix!=body[:16] or stop[:2]!=bytes.fromhex('7513'):raise ValueError('cwd_lock_body')
    spans=[(m['wrapper']['targetRva'],28),(m['prologue']['targetRva'],59),(m['scopeRva'],12),(m['handlerRva'],16),(m['cleanupRva'],16),(f['targetRva'],33),(p['tableRva']+52,16)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+c and q<r+n for q,c in spans[:i]):raise ValueError('cwd_lock_overlap')
    frame=f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,'+byte_array(f['callHex'])+','+byte_array(f['targetPrefixHex'])+'}'
    return '\n'.join(['// Generated by tools/cwd_lock_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_lock.hpp"','#include "saex/engine/cwd_seh_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_seh_digest == "{p["sehPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_lock_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_lock_digest="{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr CwdLockSpec reviewed_cwd_lock_spec{'+frame+f',{p["tableRva"]}U,'+byte_array(p['stopPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_lock_size')
    if not (ROOT/'docs/development/d1-cwd-lock.md').is_file():raise ValueError('cwd_lock_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_cwd_lock_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Cwd lock policy verified.' if a.check else 'Cwd lock policy generated.')
if __name__=='__main__':main()
