"""Compile explicit natural cwd-copy permission; never discover or execute code."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_query_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/cwd-copy-policy.json')
OUTPUT=Path('include/saex/engine/cwd_copy_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
CHECKS='85c074ac403d0401000077a48b4d0c85c97525'
CAPACITY='3b45107e10'
ENTRY='578b7c2408eb6e'
BODY='8b4c240cf7c103000000741d8a1183c10184d27466881783c701f7c10300000075eaeb05891783c704bafffefe7e8b0103d083f0ff33c28b1183c104a90001018174e184d2743484f67427f7c20000ff007412f7c2000000ff7402ebc789178b4424085fc36689178b442408c64702005fc36689178b4424085fc388178b4424085fc3'

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('cwd_copy_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','queryPolicySha256','reviewDocument','copierRva','checksHex','capacityHex','callHex','entryHex','bodyHex','returnPrefixHex'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('cwd_copy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-copy-before-argument-cleanup':raise ValueError('cwd_copy_identity')
    if p['queryPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('cwd_copy_parent')
    if p['reviewDocument']!='docs/development/d1-cwd-copy.md':raise ValueError('cwd_copy_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];q=json.loads(parents[0]);lock=src('contracts/engine/cwd-lock-policy.json')
    def region(r,n,code=True):
        mask=0x20000000 if code else 0x40000000
        if type(r) is not int or not 4096<=r<=layout['imageSize']-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&mask for s in layout['sections']):raise ValueError('cwd_copy_range')
    region(q['helperRva'],247);region(p['copierRva'],248)
    spans=[(q['helperRva'],247),(p['copierRva'],248),(lock['selector']['callRva'],23),(q['cookieRva'],4),(q['iatRva'],4),(lock['tableRva']+52,16)]
    for i,(r,n) in enumerate(spans):
        if any(r<b+m and b<r+n for b,m in spans[:i]):raise ValueError('cwd_copy_overlap')
    call=bytes.fromhex('8d85f4feffff5051e8')+struct.pack('<I',(p['copierRva']-q['helperRva']-231)&0xffffffff)
    for key,expected in [('checksHex',CHECKS),('capacityHex',CAPACITY),('entryHex',ENTRY),('bodyHex',BODY),('callHex',call.hex())]:
        if p[key]!=expected:raise ValueError('cwd_copy_body')
    if q['returnPrefixHex']!=CHECKS[:32]:raise ValueError('cwd_copy_query_chain')
    if not isinstance(p['returnPrefixHex'],str) or not re.fullmatch('[0-9a-f]{32}',p['returnPrefixHex']):raise ValueError('cwd_copy_return')
    return '\n'.join(['// Generated by tools/cwd_copy_policy.py. Do not edit.','#pragma once','#include "saex/engine/cwd_copy.hpp"','#include "saex/engine/cwd_query_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_query_digest == "{p["queryPolicySha256"]}");',f'inline constexpr std::string_view reviewed_cwd_copy_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_cwd_copy_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr CwdCopySpec reviewed_cwd_copy_spec{{{p["copierRva"]}U,'+byte_array(p['returnPrefixHex'])+'};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('cwd_copy_size')
    if not (ROOT/'docs/development/d1-cwd-copy.md').is_file():raise ValueError('cwd_copy_review_missing')
    result=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=result:raise ValueError('stale_cwd_copy_output')
    else:(ROOT/OUTPUT).write_text(result,encoding='utf-8',newline='\n')
    print('Cwd copy policy verified.' if a.check else 'Cwd copy policy generated.')
if __name__=='__main__':main()
