"""Generate bounded, observation-only native data from the shared engine profile."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("contracts/engine/observed-profile.json")
OUTPUT = Path("include/saex/engine/observed_profile.generated.hpp")


def bounded(value, low, high):
    if type(value) is not int or not low <= value <= high:
        raise ValueError("invalid_profile_number")
    return value


def validate(p):
    if type(p["schemaVersion"]) is not int or p["schemaVersion"] != 1 or p["observationOnly"] is not True:
        raise ValueError("profile_must_remain_observation_only")
    if not re.fullmatch(r"[a-z0-9.-]{1,96}", p["id"]) or not re.fullmatch(r"[0-9a-f]{64}", p["sha256"]):
        raise ValueError("invalid_profile_identity")
    bounded(p["fileBytes"], 64, 256 * 1024 * 1024)
    l = p["layout"]
    for k in ["timestamp", "imageBase", "entryRva", "imageSize", "headersSize", "sectionAlignment", "fileAlignment"]:
        bounded(l[k], 0, 0xffffffff)
    bounded(l["characteristics"], 0, 65535)
    bounded(l["dllCharacteristics"], 0, 65535)
    if not 1 <= len(l["sections"]) <= 96 or not 1 <= len(p["anchors"]) <= 32:
        raise ValueError("profile_collection_limit")
    for s in l["sections"]:
        if not re.fullmatch(r"[A-Za-z0-9_.]{1,8}", s["name"]):
            raise ValueError("invalid_section_name")
        for k in ["virtualSize", "rva", "rawSize", "rawOffset", "characteristics"]:
            bounded(s[k], 0, 0xffffffff)
    names = set()
    for a in p["anchors"]:
        if a["runtimeVerified"] is not False:
            raise ValueError("anchor_runtime_evidence_requires_new_contract")
        if not re.fullmatch(r"[a-z0-9.-]{1,64}", a["id"]) or a["id"] in names:
            raise ValueError("invalid_anchor_id")
        names.add(a["id"])
        bounded(a["rva"], 0, 0xffffffff)
        bounded(a["sectionIndex"], 0, len(l["sections"]) - 1)
        if not re.fullmatch(r"(?:[0-9a-f]{2}){1,16}", a["bytes"]):
            raise ValueError("invalid_anchor_bytes")
        s = l["sections"][a["sectionIndex"]]
        if not s["characteristics"] & 0x20000000 or not s["rva"] <= a["rva"] or a["rva"] - s["rva"] + len(a["bytes"]) // 2 > s["rawSize"]:
            raise ValueError("anchor_outside_executable_raw_section")


def byte_array(hex_value):
    return "{" + ", ".join("std::byte{0x" + hex_value[i:i+2] + "}" for i in range(0, len(hex_value), 2)) + "}"


def generate(p, source_digest):
    validate(p)
    l = p["layout"]
    lines = ["// Generated by tools/engine_profiles.py; do not edit.", '#pragma once', '#include "saex/engine/profile_gate.hpp"',
             "namespace saex::engine {", f'inline constexpr std::string_view observed_profile_source_digest = "{source_digest}";',
             "inline constexpr PeLayout observed_layout = [] {", "    PeLayout l{};"]
    keys = {"timestamp": "timestamp", "imageBase": "image_base", "entryRva": "entry_rva", "imageSize": "image_size", "headersSize": "headers_size", "sectionAlignment": "section_alignment", "fileAlignment": "file_alignment", "characteristics": "characteristics", "dllCharacteristics": "dll_characteristics"}
    for source, native in keys.items():
        lines.append(f"    l.{native} = {l[source]}U;")
    lines.append(f'    l.section_count = {len(l["sections"])};')
    for i, s in enumerate(l["sections"]):
        chars = "{" + ", ".join("'" + c + "'" for c in s["name"]) + "}"
        numbers = ", ".join(str(s[k]) + "U" for k in ["virtualSize", "rva", "rawSize", "rawOffset", "characteristics"])
        lines.append(f"    l.sections[{i}] = PeSection{{{chars}, {numbers}}};")
    lines += ["    return l;", "}();", f'inline constexpr std::array<ImageAnchor, {len(p["anchors"])}> observed_anchors{{{{']
    for a in p["anchors"]:
        lines.append(f'    ImageAnchor{{"{a["id"]}", {a["rva"]}U, {a["sectionIndex"]}, {len(a["bytes"]) // 2}, {byte_array(a["bytes"])}}},')
    lines += ["}};", f'inline constexpr ObservedProfile observed_profile{{"{p["id"]}", {p["fileBytes"]}U, {byte_array(p["sha256"])}, observed_layout, observed_anchors}};', "}", ""]
    return "\n".join(lines)


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate_profile_key")
        result[key] = value
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = (ROOT / SOURCE).read_bytes()
    if len(data) > 65536:
        raise ValueError("profile_size_limit")
    output = generate(json.loads(data, object_pairs_hook=unique_object), hashlib.sha256(data).hexdigest())
    target = ROOT / OUTPUT
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != output:
            raise SystemExit("Observed engine profile generation is stale")
        print("Observed engine profile generation verified.")
    else:
        target.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
