"""Compile the bounded dispatcher prologue, stopping BEFORE AppEventHandler."""
import argparse,hashlib,json,re
from pathlib import Path
import instance_startup_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/event-dispatch-policy.json')
OUTPUT=Path('include/saex/engine/event_dispatch_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('dispatch_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p)!={'schemaVersion','id','stage','instancePolicySha256','reviewDocument','dispatcher','application','applicationPrefixHex','branchHex'}:raise ValueError('dispatch_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-application-event-call':raise ValueError('dispatch_identity')
    if p['instancePolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('dispatch_parent')
    if p['reviewDocument']!='docs/development/d1-event-dispatch.md':raise ValueError('dispatch_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout'];size=layout['imageSize'];base=layout['imageBase'];instance=json.loads(parents[0])
    frames=[]
    for key in ('dispatcher','application'):
        f=p[key]
        if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('dispatch_frame')
        for k,n in [('callRva',5),('targetRva',17 if key=='dispatcher' else 21)]:
            v=f[k]
            if type(v) is not int or not 4096<=v<=size-n or not any(s['rva']<=v and v+n<=s['rva']+s['rawSize'] and s['characteristics']&0x20000000 for s in layout['sections']):raise ValueError('dispatch_range')
        for k,n in [('callHex',10),('targetPrefixHex',32)]:
            if not isinstance(f[k],str) or not re.fullmatch('[0-9a-f]{'+str(n)+'}',f[k]):raise ValueError('dispatch_hex')
        call=bytes.fromhex(f['callHex'])
        if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']:raise ValueError('dispatch_call')
        frames.append(f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,'+byte_array(f['callHex'])+','+byte_array(f['targetPrefixHex'])+'}')
    a,b=p['dispatcher'],p['application']
    if p['branchHex']!='85c0750f536a18' or a['callRva']!=instance['callRva']+12 or b['callRva']!=a['targetRva']+12 or a['targetPrefixHex']!='568b74240c578b7c240c5657'+b['callHex'][:8]:raise ValueError('dispatch_chain')
    if not isinstance(p['applicationPrefixHex'],str) or not re.fullmatch('[0-9a-f]{42}',p['applicationPrefixHex']) or p['applicationPrefixHex'][:32]!=b['targetPrefixHex']:raise ValueError('dispatch_application_sample')
    spans=[(a['callRva']-7,12),(a['targetRva'],17),(b['targetRva'],21),(instance['targetRva'],91)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+m and q<r+n for q,m in spans[:i]):raise ValueError('dispatch_overlap')
    return '\n'.join(['// Generated by tools/event_dispatch_policy.py. Do not edit.','#pragma once','#include "saex/engine/event_dispatch.hpp"','#include "saex/engine/instance_startup_policy.generated.hpp"','namespace saex::engine {',f'static_assert(reviewed_instance_digest == "{p["instancePolicySha256"]}");',f'inline constexpr std::string_view reviewed_dispatch_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_dispatch_digest="{hashlib.sha256(data).hexdigest()}";', 'inline constexpr EventDispatchSpec reviewed_dispatch_spec{'+','.join(frames)+','+byte_array(p['applicationPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('dispatch_size')
    if not (ROOT/'docs/development/d1-event-dispatch.md').is_file():raise ValueError('dispatch_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_dispatch_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Event dispatch policy verified.' if a.check else 'Event dispatch policy generated.')
if __name__=='__main__':main()
