"""Compile the reviewed file-manager prologue; never admit the cwd call tree."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import game_prelude_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/file-manager-entry-policy.json')
OUTPUT=Path('include/saex/engine/file_manager_entry_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('file_manager_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p)!={'schemaVersion','id','stage','preludePolicySha256','reviewDocument','manager','cwdRva','bufferRva','suffixRva','bodyHex','returnPrefixHex'}:raise ValueError('file_manager_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-cwd-call':raise ValueError('file_manager_identity')
    if p['preludePolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('file_manager_parent')
    if p['reviewDocument']!='docs/development/d1-file-manager-entry.md':raise ValueError('file_manager_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout'];base=layout['imageBase'];size=layout['imageSize']
    prelude=json.loads(parents[0]);routing=json.loads(parents[1])['initializer']
    def region(r,n,kind='code'):
        mask={'code':0x20000000,'data':0xc0000000,'literal':0x40000000}[kind]
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['virtualSize' if kind=='data' else 'rawSize'] and s['characteristics']&mask==mask for s in layout['sections']):raise ValueError('file_manager_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(2*n)+'}',v):raise ValueError('file_manager_hex')
        return bytes.fromhex(v)
    f=p['manager']
    if type(f) is not dict or set(f)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('file_manager_frame')
    region(f['callRva'],21);region(f['targetRva'],51);region(p['cwdRva'],16);region(p['suffixRva'],2,'literal')
    if type(p['bufferRva']) is not int or p['bufferRva']<4100:raise ValueError('file_manager_buffer')
    region(p['bufferRva']-4,136,'data')
    call=hx(f['callHex'],5);prefix=hx(f['targetPrefixHex'],16);stop=hx(p['returnPrefixHex'],16)
    if call[0]!=0xe8 or f['callRva']+5+int.from_bytes(call[1:],'little',signed=True)!=f['targetRva']:raise ValueError('file_manager_call')
    if f['callRva']!=prelude['localisation']['callRva']+5 or call+stop[:11]!=bytes.fromhex(prelude['stopPrefixHex']):raise ValueError('file_manager_chain')
    body=bytearray.fromhex('5768800000006800000000e800000000bf0000000083c4084f8da424000000008a47014784c075f866a1000000006689075fc3')
    for offset,value in ((7,base+p['bufferRva']),(17,base+p['bufferRva']),(42,base+p['suffixRva'])):struct.pack_into('<I',body,offset,value)
    struct.pack_into('<i',body,12,p['cwdRva']-f['targetRva']-16)
    if hx(p['bodyHex'],51)!=body or prefix!=body[:16]:raise ValueError('file_manager_body')
    spans=[(routing['callRva'],5),(routing['targetRva'],31),(prelude['empty']['targetRva'],16),(prelude['localisation']['targetRva'],20),
        (prelude['flagsRva']-4,16),(f['targetRva'],51),(p['cwdRva'],16),(p['bufferRva']-4,136),(p['suffixRva'],2)]
    region(routing['targetRva'],31)
    for i,(r,n) in enumerate(spans):
        if any(r<q+m and q<r+n for q,m in spans[:i]):raise ValueError('file_manager_overlap')
    frame=f'FrameTargetSpec{{{base}U,{size}U,{f["callRva"]}U,{f["targetRva"]}U,'+byte_array(f['callHex'])+','+byte_array(f['targetPrefixHex'])+'}'
    return '\n'.join(['// Generated by tools/file_manager_entry_policy.py. Do not edit.','#pragma once','#include "saex/engine/file_manager_entry.hpp"','#include "saex/engine/game_prelude_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_prelude_digest == "{p["preludePolicySha256"]}");',f'inline constexpr std::string_view reviewed_file_manager_id="{p["id"]}";',
        f'inline constexpr std::string_view reviewed_file_manager_digest="{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr FileManagerEntrySpec reviewed_file_manager_spec{'+frame+f',{p["cwdRva"]}U,{p["bufferRva"]}U,{p["suffixRva"]}U,'+byte_array(p['returnPrefixHex'])+'};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('file_manager_size')
    if not (ROOT/'docs/development/d1-file-manager-entry.md').is_file():raise ValueError('file_manager_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_file_manager_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('File manager entry policy verified.' if a.check else 'File manager entry policy generated.')
if __name__=='__main__':main()
