"""Compile the reviewed complete CFileMgr return permission; no binary discovery."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import cwd_return_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/file-manager-ready-policy.json')
OUTPUT=Path('include/saex/engine/file_manager_ready_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('file_manager_ready_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','returnPolicySha256','reviewDocument','unlockRva','iatRva','epilogueRva','wrapperHex','cleanupHex','unlockHex','epilogueHex','function','systemModule'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('file_manager_ready_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='after-file-manager-return':raise ValueError('file_manager_ready_identity')
    if p['returnPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('file_manager_ready_parent')
    if p['reviewDocument']!='docs/development/d1-file-manager-ready.md':raise ValueError('file_manager_ready_review')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout'];base=layout['imageBase'];size=layout['imageSize']
    l=src('contracts/engine/cwd-lock-policy.json');seh=src('contracts/engine/cwd-seh-policy.json');m=src('contracts/engine/file-manager-entry-policy.json')
    def region(r,n,code=True):
        mask=0x20000000 if code else 0x40000000
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize'] and s['characteristics']&mask for s in layout['sections']):raise ValueError('file_manager_ready_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(n*2)+'}',v):raise ValueError('file_manager_ready_hex')
        return bytes.fromhex(v)
    start=l['selector']['callRva']+23;cleanup=seh['cleanupRva'];unlock=p['unlockRva'];epilogue=p['epilogueRva']
    for r,n in [(start,24),(cleanup,9),(unlock,21),(epilogue,17)]:region(r,n)
    region(p['iatRva'],4,False)
    if p['iatRva']%4:raise ValueError('file_manager_ready_alignment')
    spans=[(start,24),(cleanup,9),(unlock,21),(epilogue,17),(p['iatRva'],4),(l['tableRva']+52,16),(m['manager']['targetRva'],51),(m['manager']['callRva'],21),(m['bufferRva']-4,136),(m['suffixRva'],2)]
    for i,(r,n) in enumerate(spans):
        if any(r<b+c and b<r+n for b,c in spans[:i]):raise ValueError('file_manager_ready_overlap')
    u32=lambda v:struct.pack('<I',v&0xffffffff)
    wrapper=bytes.fromhex('83c40c8945e4834dfcffe8')+u32(cleanup-start-15)+bytes.fromhex('8b45e4e8')+u32(epilogue-start-23)+b'\xc3'
    bodies={'wrapperHex':wrapper,'cleanupHex':b'\x6a\x07\xe8'+u32(unlock-cleanup-7)+b'\x59\xc3',
        'unlockHex':bytes.fromhex('558bec8b4508ff34c5')+u32(base+l['tableRva'])+b'\xff\x15'+u32(base+p['iatRva'])+b'\x5d\xc3',
        'epilogueHex':bytes.fromhex('8b4df064890d00000000595f5e5bc951c3')}
    for key,value in bodies.items():
        if hx(p[key],len(value))!=value:raise ValueError('file_manager_ready_body')
    if wrapper[:16]!=bytes.fromhex(json.loads(parents[0])['returnPrefixHex']):raise ValueError('file_manager_ready_chain')
    module=p['systemModule'];expected=next(v for v in src('contracts/engine/loader-policy.json')['modules'] if v['name']=='ntdll.dll')
    if type(module) is not dict or set(module)!={'name','bytes','sha256'} or type(module['bytes']) is not int or module!={k:expected[k] for k in module}:raise ValueError('file_manager_ready_module')
    f=p['function']
    if type(f) is not dict or set(f)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('file_manager_ready_function')
    if type(f['rva']) is not int or not 4096<=f['rva']<16*1024*1024-20 or type(f['preferredBase']) is not int or not 0<f['preferredBase']<=0xffff0000 or f['preferredBase']%65536 or f['highlowOffsets']!=[]:raise ValueError('file_manager_ready_function_range')
    hx(f['prefixHex'],20)
    return '\n'.join(['// Generated by tools/file_manager_ready_policy.py. Do not edit.','#pragma once','#include "saex/engine/file_manager_ready.hpp"','#include "saex/engine/cwd_return_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_cwd_return_digest == "{p["returnPolicySha256"]}");',f'inline constexpr std::string_view reviewed_file_manager_ready_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_file_manager_ready_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr FileManagerReadySpec reviewed_file_manager_ready_spec{{{unlock}U,{p["iatRva"]}U,{epilogue}U,BootstrapExportSpec{{{f["rva"]}U,'+byte_array(f['prefixHex'])+f',{f["preferredBase"]}U,0U'+'}};','}',''])

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('file_manager_ready_size')
    if not (ROOT/'docs/development/d1-file-manager-ready.md').is_file():raise ValueError('file_manager_ready_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_file_manager_ready_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('File manager ready policy verified.' if a.check else 'File manager ready policy generated.')
if __name__=='__main__':main()
