"""Compile a read-only frame candidate; never promote it to a callable binding."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import bootstrap_lifecycle_policy as parent
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/frame-target-policy.json')
OUTPUT = Path('include/saex/engine/frame_target_policy.generated.hpp')
SOURCES = (SOURCE, Path('contracts/engine/observed-profile.json'), *parent.SOURCES)


def byte_array(value):
    return '{' + ', '.join(f'std::byte{{0x{byte:02x}}}' for byte in bytes.fromhex(value)) + '}'


def compile_source(data, observed, *parents):
    if max(map(len, (data, observed, *parents))) > 65536: raise ValueError('frame_policy_size')
    parent.compile_source(*parents)
    p = json.loads(data, object_pairs_hook=loader_policy.strict_object)
    profile = json.loads(observed, object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion', 'id', 'stage', 'bootstrapPolicySha256', 'profileSourceSha256',
            'reviewDocument', 'callRva', 'targetRva', 'callHex', 'targetPrefixHex', 'sourceEvidence'}
    if type(p) is not dict or set(p) != keys: raise ValueError('frame_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'read-only-frame-candidate':
        raise ValueError('frame_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', p['id']): raise ValueError('frame_policy_id')
    if p['bootstrapPolicySha256'] != hashlib.sha256(parents[0]).hexdigest() or p['profileSourceSha256'] != hashlib.sha256(observed).hexdigest():
        raise ValueError('frame_policy_parent_drift')
    if p['reviewDocument'] != 'docs/development/d1-frame-target.md': raise ValueError('frame_policy_review')
    for key, length in [('callHex', 10), ('targetPrefixHex', 32)]:
        if not isinstance(p[key], str) or not re.fullmatch('[0-9a-f]{'+str(length)+'}', p[key]): raise ValueError('frame_policy_hex')
    call = bytes.fromhex(p['callHex'])
    size = profile['layout']['imageSize']
    for key, length in [('callRva', 5), ('targetRva', 16)]:
        rva = p[key]
        if type(rva) is not int or not 4096 <= rva <= size-length: raise ValueError('frame_policy_range')
        if not any(s['characteristics'] & 0x20000000 and s['rva'] <= rva and rva+length <= s['rva']+s['rawSize']
                   for s in profile['layout']['sections']): raise ValueError('frame_policy_section')
    if p['callRva'] < p['targetRva']+16 and p['targetRva'] < p['callRva']+5: raise ValueError('frame_policy_overlap')
    if call[0] != 0xe8 or p['callRva']+5+int.from_bytes(call[1:], 'little', signed=True) != p['targetRva']:
        raise ValueError('frame_policy_call')
    anchor = next(a for a in profile['anchors'] if a['id'] == 'game-process-call')
    if (p['callRva'], p['targetRva'], p['callHex']) != (anchor['rva'], anchor['diskRelativeTargetRva'], anchor['bytes']):
        raise ValueError('frame_policy_anchor')
    sources = p['sourceEvidence']
    expected_paths = ['shared/Events.h', 'plugin_sa/game_sa/CGame.cpp', 'plugin_sa/game_sa/CGame.h']
    if type(sources) is not list or len(sources) != 3: raise ValueError('frame_policy_sources')
    for entry, path in zip(sources, expected_paths):
        if type(entry) is not dict or set(entry) != {'path', 'sha256'} or entry['path'] != path or not isinstance(entry['sha256'], str) or not re.fullmatch('[0-9a-f]{64}', entry['sha256']) or entry['sha256'] == '0'*64:
            raise ValueError('frame_policy_source')
    return '\n'.join(['// Generated by tools/frame_target_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/frame_target.hpp"', '#include "saex/engine/bootstrap_lifecycle_policy.generated.hpp"',
        '#include "saex/engine/observed_profile.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_bootstrap_policy_digest == "{p["bootstrapPolicySha256"]}");',
        f'static_assert(observed_profile_source_digest == "{p["profileSourceSha256"]}");',
        f'inline constexpr std::string_view reviewed_frame_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_frame_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr FrameTargetSpec reviewed_frame_spec{{{profile["layout"]["imageBase"]}U, {size}U, {p["callRva"]}U, {p["targetRva"]}U, {byte_array(p["callHex"])}, {byte_array(p["targetPrefixHex"])}}};',
        '}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT/p for p in SOURCES]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('frame_policy_size')
    if not (ROOT/'docs/development/d1-frame-target.md').is_file(): raise ValueError('frame_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8') != output: raise ValueError('stale_frame_policy_output')
    else: (ROOT/OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Read-only frame candidate policy verified.' if args.check else 'Read-only frame candidate policy generated.')


if __name__ == '__main__': main()
