"""Compile two reviewed pre-RW helpers; stop before file manager initialization."""
import argparse,hashlib,json,re,struct
from pathlib import Path
import application_routing_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/game-prelude-policy.json')
OUTPUT=Path('include/saex/engine/game_prelude_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('prelude_size')
    parent.compile_source(*parents);p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    if type(p) is not dict or set(p)!={'schemaVersion','id','stage','routingPolicySha256','reviewDocument','empty','localisation','flagsRva','localisationBodyHex','stopPrefixHex'}:raise ValueError('prelude_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']) or p['stage']!='before-file-manager-call':raise ValueError('prelude_identity')
    if p['routingPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('prelude_parent')
    if p['reviewDocument']!='docs/development/d1-game-prelude.md':raise ValueError('prelude_review')
    layout=json.loads(parents[parent.SOURCES.index(Path('contracts/engine/observed-profile.json'))])['layout'];base=layout['imageBase'];size=layout['imageSize'];f=json.loads(parents[0])['initializer']
    def region(r,n,code=True):
        if type(r) is not int or not 4096<=r<=size-n or not any(s['rva']<=r and r+n<=s['rva']+s['rawSize' if code else 'virtualSize'] and (s['characteristics']&(0x20000000 if code else 0xc0000000))==(0x20000000 if code else 0xc0000000) for s in layout['sections']):raise ValueError('prelude_range')
    def hx(v,n):
        if not isinstance(v,str) or not re.fullmatch('[0-9a-f]{'+str(n*2)+'}',v):raise ValueError('prelude_hex')
        return bytes.fromhex(v)
    frames=[]
    for key in ('empty','localisation'):
        a=p[key]
        if type(a) is not dict or set(a)!={'callRva','targetRva','callHex','targetPrefixHex'}:raise ValueError('prelude_frame')
        region(a['callRva'],5);region(a['targetRva'],16 if key=='empty' else 20)
        c=hx(a['callHex'],5);hx(a['targetPrefixHex'],16)
        if c[0]!=0xe8 or a['callRva']+5+int.from_bytes(c[1:],'little',signed=True)!=a['targetRva']:raise ValueError('prelude_call')
        frames.append(f'FrameTargetSpec{{{base}U,{size}U,{a["callRva"]}U,{a["targetRva"]}U,'+byte_array(a['callHex'])+','+byte_array(a['targetPrefixHex'])+'}')
    a,b=p['empty'],p['localisation'];stop=hx(p['stopPrefixHex'],16)
    if a['callRva']!=f['targetRva'] or b['callRva']!=a['callRva']+5 or a['targetPrefixHex']!='c3'+'90'*15 or a['callHex']+b['callHex']+stop[:6].hex()!=f['targetPrefixHex']:raise ValueError('prelude_chain')
    if type(p['flagsRva']) is not int or p['flagsRva']<4100:raise ValueError('prelude_flags')
    region(p['flagsRva']-4,16,False)
    addr=lambda i:struct.pack('<I',base+p['flagsRva']+i)
    body=b'\x32\xc0\xc6\x05'+addr(0)+b'\x01\xa2'+addr(1)+b'\xa2'+addr(2)+b'\xc3'
    if hx(p['localisationBodyHex'],20)!=body or b['targetPrefixHex']!=body[:16].hex():raise ValueError('prelude_body')
    region(f['targetRva'],26)
    spans=[(f['callRva'],5),(f['targetRva'],26),(a['targetRva'],16),(b['targetRva'],20),(p['flagsRva']-4,16)]
    for i,(r,n) in enumerate(spans):
        if any(r<q+m and q<r+n for q,m in spans[:i]):raise ValueError('prelude_overlap')
    return '\n'.join(['// Generated by tools/game_prelude_policy.py. Do not edit.','#pragma once','#include "saex/engine/game_prelude.hpp"','#include "saex/engine/application_routing_policy.generated.hpp"','namespace saex::engine {',f'static_assert(reviewed_routing_digest == "{p["routingPolicySha256"]}");',f'inline constexpr std::string_view reviewed_prelude_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_prelude_digest="{hashlib.sha256(data).hexdigest()}";', 'inline constexpr GamePreludeSpec reviewed_prelude_spec{'+','.join(frames)+f',{p["flagsRva"]}U,'+byte_array(p['stopPrefixHex'])+'};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args();paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('prelude_size')
    if not (ROOT/'docs/development/d1-game-prelude.md').is_file():raise ValueError('prelude_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_prelude_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Game prelude policy verified.' if a.check else 'Game prelude policy generated.')
if __name__=='__main__':main()
