"""Compile an explicitly reviewed mapping-only policy; never discover or approve DLLs."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/loader-policy.json')
OUTPUT = Path('include/saex/engine/loader_policy.generated.hpp')


def strict_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result: raise ValueError('duplicate_json_key')
        result[key] = value
    return result


def validate(policy):
    keys = {'schemaVersion', 'id', 'stage', 'engineSha256', 'reviewDocument', 'modules'}
    if type(policy) is not dict or set(policy) != keys: raise ValueError('policy_keys')
    if type(policy['schemaVersion']) is not int or policy['schemaVersion'] != 1 or policy['stage'] != 'first-exception-only':
        raise ValueError('policy_must_remain_mapping_only')
    if not isinstance(policy['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', policy['id']): raise ValueError('policy_id')
    def digest(value):
        return isinstance(value, str) and re.fullmatch(r'[0-9a-f]{64}', value) and value != '0' * 64
    if not digest(policy['engineSha256']): raise ValueError('policy_engine_hash')
    if policy['reviewDocument'] != 'docs/development/d1-loader-policy.md': raise ValueError('policy_review_document')
    modules = policy['modules']
    if type(modules) is not list or not 1 <= len(modules) <= 64: raise ValueError('policy_module_limit')
    names, total = set(), 0
    for module in modules:
        if type(module) is not dict or set(module) != {'origin','name','bytes','sha256','basis'}: raise ValueError('policy_module_keys')
        name = module['name']
        if not isinstance(name, str) or not re.fullmatch(r'[a-z0-9_.-]{1,123}\.dll', name) or '..' in name: raise ValueError('policy_module_name')
        if name in names: raise ValueError('policy_duplicate_module')
        names.add(name)
        if module['origin'] not in ('system-x86','game-root'): raise ValueError('policy_origin')
        if type(module['bytes']) is not int or not 1 <= module['bytes'] <= 64 * 1024 * 1024: raise ValueError('policy_module_bytes')
        if not digest(module['sha256']): raise ValueError('policy_module_hash')
        if module['basis'] not in ('loader-system','compatibility-infrastructure','gta-static-import','transitive-static-import','api-set-host-candidate'):
            raise ValueError('policy_module_basis')
        total += module['bytes']
    if total > 256 * 1024 * 1024: raise ValueError('policy_total_bytes')
    if [m['name'] for m in modules] != sorted(names): raise ValueError('policy_module_order')


def byte_array(value):
    return '{' + ', '.join('std::byte{0x' + value[i:i+2] + '}' for i in range(0,64,2)) + '}'


def generate(policy, digest):
    validate(policy)
    lines = ['// Generated by tools/loader_policy.py; do not edit.', '#pragma once',
             '#include "saex/engine/loader_policy.hpp"', 'namespace saex::engine {',
             f'inline constexpr std::string_view reviewed_loader_policy_id = "{policy["id"]}";',
             f'inline constexpr std::string_view reviewed_loader_policy_digest = "{digest}";',
             f'inline constexpr Sha256 reviewed_loader_engine_hash = {byte_array(policy["engineSha256"])};',
             f'inline constexpr std::array<LoaderPinSpec, {len(policy["modules"])}> reviewed_loader_specs{{{{']
    for module in policy['modules']:
        origin = module['origin'].replace('-', '_')
        lines.append(f'    LoaderPinSpec{{LoaderOrigin::{origin}, "{module["name"]}", {module["bytes"]}ULL, {byte_array(module["sha256"])}}},')
    return '\n'.join(lines + ['}};', '}', ''])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / SOURCE
    if path.stat().st_size > 65536: raise ValueError('policy_source_size')
    data = path.read_bytes()
    policy = json.loads(data.decode('utf-8'), object_pairs_hook=strict_object)
    validate(policy)
    engine = json.loads((ROOT / 'contracts/engine/observed-profile.json').read_text(encoding='utf-8'))
    if policy['engineSha256'] != engine['sha256']: raise ValueError('policy_engine_profile_mismatch')
    if not (ROOT / policy['reviewDocument']).is_file(): raise ValueError('policy_review_missing')
    output = generate(policy, hashlib.sha256(data).hexdigest())
    if args.check:
        if not (ROOT / OUTPUT).is_file() or (ROOT / OUTPUT).read_text(encoding='utf-8') != output:
            raise ValueError('stale_loader_policy_generated_output')
    else: (ROOT / OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed loader mapping policy verified.' if args.check else 'Reviewed loader mapping policy generated.')


if __name__ == '__main__': main()
