"""Compile one exact local CALL suppression and its audited last-error reader."""
import argparse,hashlib,json,re
from pathlib import Path
import platform_startup_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/platform-suppression-policy.json')
OUTPUT=Path('include/saex/engine/platform_suppression_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('suppression_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','platformPolicySha256','reviewDocument','method','returnValue','preserveLastError','lastErrorIatRva','lastErrorModule','lastErrorFunction'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('suppression_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']):raise ValueError('suppression_identity')
    if p['platformPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('suppression_parent')
    if p['reviewDocument']!='docs/development/d1-platform-suppression.md':raise ValueError('suppression_review')
    if p['method']!='owned-context-false-return' or type(p['returnValue']) is not int or p['returnValue']!=0 or p['preserveLastError'] is not True:raise ValueError('suppression_behavior')
    def src(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    layout=src('contracts/engine/observed-profile.json')['layout']; platform=json.loads(parents[0]);r=p['lastErrorIatRva']
    if type(r) is not int or r%4 or not 4096<=r<=layout['imageSize']-4 or r==platform['iatRva'] or not any(s['rva']<=r and r+4<=s['rva']+s['rawSize'] and not s['characteristics']&0x20000000 for s in layout['sections']):raise ValueError('suppression_iat')
    m=p['lastErrorModule'];expected=next(x for x in src('contracts/engine/loader-policy.json')['modules'] if x['name']=='kernel32.dll')
    if type(m) is not dict or set(m)!={'name','bytes','sha256'} or type(m['bytes']) is not int or m!={k:expected[k] for k in m}:raise ValueError('suppression_module')
    f=p['lastErrorFunction']
    if type(f) is not dict or set(f)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('suppression_function')
    if type(f['rva']) is not int or not 0<f['rva']<16*1024*1024-20 or type(f['preferredBase']) is not int or not 0<f['preferredBase']<=0xffff0000 or f['preferredBase']%65536:raise ValueError('suppression_function_range')
    if not isinstance(f['prefixHex'],str) or not re.fullmatch('64a134000000c3[0-9a-f]{26}',f['prefixHex']) or f['highlowOffsets']!=[]:raise ValueError('suppression_last_error_shape')
    return '\n'.join(['// Generated by tools/platform_suppression_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/platform_suppression.hpp"','#include "saex/engine/platform_startup_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_platform_digest == "{p["platformPolicySha256"]}");',
        f'inline constexpr std::string_view reviewed_suppression_id="{p["id"]}";',
        f'inline constexpr std::string_view reviewed_suppression_digest="{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr PlatformSuppressionSpec reviewed_suppression_spec{'+str(r)+'U, BootstrapExportSpec{'+str(f['rva'])+'U,'+byte_array(f['prefixHex'])+f',{f["preferredBase"]}U,0U'+'}};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('suppression_size')
    if not (ROOT/'docs/development/d1-platform-suppression.md').is_file():raise ValueError('suppression_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_suppression_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Platform suppression policy verified.' if a.check else 'Platform suppression policy generated.')
if __name__=='__main__':main()
