"""Compile a stop BEFORE the application's system-wide settings call; never allow it."""
import argparse,hashlib,json,re
from pathlib import Path
import application_entry_policy as parent
import loader_policy
from frame_target_policy import byte_array
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/platform-startup-policy.json')
OUTPUT=Path('include/saex/engine/platform_startup_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)
def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536:raise ValueError('platform_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','applicationPolicySha256','reviewDocument','prologueHex','callRva','iatRva','returnPrefixHex','systemModule','function','arguments','stackBytes'}
    if type(p) is not dict or set(p)!=keys:raise ValueError('platform_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or p['stage']!='before-system-parameter-call':raise ValueError('platform_stage')
    if not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']):raise ValueError('platform_id')
    if p['applicationPolicySha256']!=hashlib.sha256(parents[0]).hexdigest():raise ValueError('platform_parent')
    if p['reviewDocument']!='docs/development/d1-platform-startup.md':raise ValueError('platform_review')
    if type(p['stackBytes']) is not int or p['stackBytes']!=152 or type(p['arguments']) is not list or p['arguments']!=[8193,0,0,2] or any(type(v) is not int for v in p['arguments']):raise ValueError('platform_abi')
    def source(name):return json.loads(parents[parent.SOURCES.index(Path(name))])
    crt=source('contracts/engine/crt-startup-policy.json');layout=source('contracts/engine/observed-profile.json')['layout'];app=json.loads(parents[0])
    if not isinstance(p['prologueHex'],str) or not re.fullmatch('[0-9a-f]{32,512}',p['prologueHex']) or len(p['prologueHex'])%2:raise ValueError('platform_prologue')
    n=len(p['prologueHex'])//2;start=crt['application']['targetRva']
    if p['prologueHex'][:32]!=crt['application']['targetPrefixHex'] or type(p['callRva']) is not int or p['callRva']!=start+n:raise ValueError('platform_call')
    if type(p['iatRva']) is not int or p['iatRva']%4:raise ValueError('platform_iat')
    if not isinstance(p['returnPrefixHex'],str) or not re.fullmatch('[0-9a-f]{32}',p['returnPrefixHex']):raise ValueError('platform_return')
    spans=[(start,n+22),(p['iatRva'],4)]
    for r,size in spans:
        if not 4096<=r<=layout['imageSize']-size or not any(s['rva']<=r and r+size<=s['rva']+s['rawSize'] and (r==p['iatRva'] or s['characteristics']&0x20000000) for s in layout['sections']):raise ValueError('platform_range')
    spans += [(crt[k]['callRva'],21 if k!='application' else 5) for k in ('io','initialize','application')]
    spans += [(crt['io']['targetRva'],16),(crt['initialize']['targetRva'],len(app['initializerBodyHex'])//2),(app['secondCallRva'],22)]
    spans += [(t['rva'],len(t['targets'])*4) for t in crt['tables']]
    for i,(r,n) in enumerate(spans):
        if any(r<b+m and b<r+n for b,m in spans[:i]):raise ValueError('platform_overlap')
    expected=next(m for m in source('contracts/engine/loader-policy.json')['modules'] if m['name']=='user32.dll')
    m=p['systemModule']
    if type(m) is not dict or set(m)!={'name','bytes','sha256'} or type(m['bytes']) is not int or m!={k:expected[k] for k in m}:raise ValueError('platform_module')
    f=p['function']
    if type(f) is not dict or set(f)!={'rva','prefixHex','preferredBase','highlowOffsets'}:raise ValueError('platform_function')
    if type(f['rva']) is not int or not 0<f['rva']<16*1024*1024-20:raise ValueError('platform_function_rva')
    if not isinstance(f['prefixHex'],str) or not re.fullmatch('[0-9a-f]{40}',f['prefixHex']):raise ValueError('platform_function_prefix')
    if type(f['preferredBase']) is not int or not 0<f['preferredBase']<=0xffff0000 or f['preferredBase']%65536:raise ValueError('platform_base')
    offsets=f['highlowOffsets']
    if type(offsets) is not list or any(type(x) is not int or not 0<=x<=16 for x in offsets) or offsets!=sorted(set(offsets)) or any(b<a+4 for a,b in zip(offsets,offsets[1:])):raise ValueError('platform_fixups')
    return '\n'.join(['// Generated by tools/platform_startup_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/platform_startup.hpp"','#include "saex/engine/application_entry_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_application_policy_digest == "{p["applicationPolicySha256"]}");',
        'static_assert(platform_startup_arguments == std::array<std::uint32_t,4>{8193,0,0,2});',
        f'inline constexpr std::string_view reviewed_platform_id="{p["id"]}";',f'inline constexpr std::string_view reviewed_platform_digest="{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr std::array<std::byte,{len(p["prologueHex"])//2}> reviewed_platform_prologue'+byte_array(p['prologueHex'])+';',
        'inline constexpr PlatformStartupSpec reviewed_platform_spec{reviewed_platform_prologue,'+f'{p["callRva"]}U,{p["iatRva"]}U,152U,'+byte_array(p['returnPrefixHex'])+',',
        'BootstrapExportSpec{'+str(f['rva'])+'U,'+byte_array(f['prefixHex'])+f',{f["preferredBase"]}U,{sum(1<<i for i in offsets)}U'+'}};','}',''])
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths):raise ValueError('platform_size')
    if not (ROOT/'docs/development/d1-platform-startup.md').is_file():raise ValueError('platform_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if a.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output:raise ValueError('stale_platform_output')
    else:(ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Platform startup policy verified.' if a.check else 'Platform startup policy generated.')
if __name__=='__main__':main()
