"""Compile a reviewed two-stop proxy recipe; never discover or approve modules."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import entry_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/proxy-policy.json')
OUTPUT = Path('include/saex/engine/proxy_policy.generated.hpp')


def compile_source(data, entry_data, base_data):
    if len(data) > 65536: raise ValueError('proxy_policy_size')
    entry_policy.compile_source(entry_data, base_data)
    policy = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion', 'id', 'stage', 'entryPolicySha256', 'module', 'moduleSha256',
            'thunkRva', 'callTargetRva', 'returnSlotRva', 'iatRva', 'iatTargetRva', 'reviewDocument'}
    if type(policy) is not dict or set(policy) != keys: raise ValueError('proxy_policy_keys')
    if type(policy['schemaVersion']) is not int or policy['schemaVersion'] != 1 or policy['stage'] != 'proxy-return-boundary':
        raise ValueError('proxy_policy_stage')
    if not isinstance(policy['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', policy['id']): raise ValueError('proxy_policy_id')
    digest = hashlib.sha256(entry_data).hexdigest()
    if policy['entryPolicySha256'] != digest: raise ValueError('proxy_policy_entry_drift')
    if policy['reviewDocument'] != 'docs/development/d1-proxy-return.md': raise ValueError('proxy_policy_review')
    base = json.loads(base_data)
    modules = [m for m in base['modules'] if m['origin'] == 'game-root' and m['name'] == policy['module'] and m['sha256'] == policy['moduleSha256']]
    if len(modules) != 1: raise ValueError('proxy_policy_module_binding')
    fields = ('thunkRva', 'callTargetRva', 'returnSlotRva', 'iatRva', 'iatTargetRva')
    for key in fields:
        if type(policy[key]) is not int or not 0 < policy[key] <= 256 * 1024 * 1024 - 16:
            raise ValueError('proxy_policy_rva')
    if policy['returnSlotRva'] % 4 or policy['iatRva'] % 4: raise ValueError('proxy_policy_alignment')
    return '\n'.join([
        '// Generated by tools/proxy_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/entry_policy.generated.hpp"', 'namespace saex::engine {',
        f'static_assert(reviewed_entry_policy_digest == "{digest}", "proxy policy entry drift");',
        f'inline constexpr std::string_view reviewed_proxy_policy_id = "{policy["id"]}";',
        f'inline constexpr std::string_view reviewed_proxy_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr std::string_view reviewed_proxy_module = "{policy["module"]}";',
        'inline constexpr ProxyStopSpec reviewed_proxy_spec{nullptr, ' + ', '.join(str(policy[f]) for f in fields) + '};',
        '}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT / SOURCE, ROOT / entry_policy.SOURCE, ROOT / loader_policy.SOURCE]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('proxy_policy_size')
    if not (ROOT / 'docs/development/d1-proxy-return.md').is_file(): raise ValueError('proxy_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT / OUTPUT).is_file() or (ROOT / OUTPUT).read_text(encoding='utf-8') != output:
            raise ValueError('stale_proxy_policy_generated_output')
    else: (ROOT / OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed proxy-return policy verified.' if args.check else 'Reviewed proxy-return policy generated.')


if __name__ == '__main__': main()
