"""Compile a separate reviewed startup-call stop; never approve dynamic modules."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import proxy_policy
import entry_policy
import loader_policy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('contracts/engine/startup-policy.json')
OUTPUT = Path('include/saex/engine/startup_policy.generated.hpp')
PROFILE = Path('contracts/engine/observed-profile.json')


def compile_source(data, proxy, entry, base, observed):
    if max(map(len, (data, proxy, entry, base, observed))) > 65536: raise ValueError('startup_policy_size')
    proxy_policy.compile_source(proxy, entry, base)
    p = json.loads(data.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    keys = {'schemaVersion','id','stage','proxyPolicySha256','observedProfileSha256',
            'callForm','stackArgumentBytes','maxImageSamples','iatWriteWatch','reviewDocument'}
    if type(p) is not dict or set(p) != keys: raise ValueError('startup_policy_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion'] != 1 or p['stage'] != 'startup-call-boundary':
        raise ValueError('startup_policy_stage')
    if not isinstance(p['id'], str) or not re.fullmatch(r'[a-z0-9.-]{1,96}', p['id']): raise ValueError('startup_policy_id')
    if p['proxyPolicySha256'] != hashlib.sha256(proxy).hexdigest(): raise ValueError('startup_policy_proxy_drift')
    if p['observedProfileSha256'] != hashlib.sha256(observed).hexdigest(): raise ValueError('startup_policy_profile_drift')
    profile = json.loads(observed.decode('utf-8'), object_pairs_hook=loader_policy.strict_object)
    if profile['sha256'] != json.loads(base)['engineSha256']: raise ValueError('startup_policy_engine_drift')
    if p['callForm'] != 'x86-ff15-iat' or type(p['stackArgumentBytes']) is not int or p['stackArgumentBytes'] != 68 or \
       type(p['maxImageSamples']) is not int or p['maxImageSamples'] != 4 or p['iatWriteWatch'] is not True:
        raise ValueError('startup_policy_boundary')
    if p['reviewDocument'] != 'docs/development/d1-startup-call.md': raise ValueError('startup_policy_review')
    return '\n'.join([
        '// Generated by tools/startup_policy.py. Do not edit.', '#pragma once',
        '#include "saex/engine/proxy_policy.generated.hpp"', '#include "saex/engine/observed_profile.generated.hpp"',
        'namespace saex::engine {',
        f'static_assert(reviewed_proxy_policy_digest == "{p["proxyPolicySha256"]}", "startup proxy drift");',
        f'static_assert(observed_profile_source_digest == "{p["observedProfileSha256"]}", "startup profile drift");',
        f'inline constexpr std::string_view reviewed_startup_policy_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_startup_policy_digest = "{hashlib.sha256(data).hexdigest()}";',
        'inline constexpr StartupStopSpec reviewed_startup_spec{observed_anchors};', '}', ''])


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    paths = [ROOT / p for p in (SOURCE, proxy_policy.SOURCE, entry_policy.SOURCE, loader_policy.SOURCE, PROFILE)]
    if any(p.stat().st_size > 65536 for p in paths): raise ValueError('startup_policy_size')
    if not (ROOT / 'docs/development/d1-startup-call.md').is_file(): raise ValueError('startup_policy_review_missing')
    output = compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT / OUTPUT).is_file() or (ROOT / OUTPUT).read_text(encoding='utf-8') != output:
            raise ValueError('stale_startup_policy_generated_output')
    else: (ROOT / OUTPUT).write_text(output, encoding='utf-8', newline='\n')
    print('Reviewed startup-call policy verified.' if args.check else 'Reviewed startup-call policy generated.')


if __name__ == '__main__': main()
