"""Explicit natural startup continuation permission; pinned parent and OS exports."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import frame_target_policy as parent
import loader_policy
ROOT=Path(__file__).resolve().parents[1]
SOURCE=Path('contracts/engine/startup-return-policy.json')
OUTPUT=Path('include/saex/engine/startup_return_policy.generated.hpp')
SOURCES=(SOURCE,*parent.SOURCES)

def compile_source(data,*parents):
    if max(map(len,(data,*parents)))>65536: raise ValueError('startup_return_size')
    parent.compile_source(*parents)
    p=json.loads(data,object_pairs_hook=loader_policy.strict_object)
    keys={'schemaVersion','id','stage','framePolicySha256','reviewDocument','protectCallRva','protectSlotRva','startupSlotRva','forwardRva','protectReturnHex','systemModule','protectFunction','startupFunction','resultProtections'}
    if type(p) is not dict or set(p)!=keys: raise ValueError('startup_return_keys')
    if type(p['schemaVersion']) is not int or p['schemaVersion']!=1 or p['stage']!='natural-startup-return': raise ValueError('startup_return_stage')
    if not isinstance(p['id'],str) or not re.fullmatch('[a-z0-9.-]{1,96}',p['id']): raise ValueError('startup_return_id')
    if p['framePolicySha256']!=hashlib.sha256(parents[0]).hexdigest(): raise ValueError('startup_return_parent')
    if p['reviewDocument']!='docs/development/d1-startup-return.md': raise ValueError('startup_return_review')
    if type(p['resultProtections']) is not list or p['resultProtections']!=[64,128] or any(type(v) is not int for v in p['resultProtections']): raise ValueError('startup_return_protections')
    spans=[]
    for key,length in [('protectCallRva',22),('protectSlotRva',4),('startupSlotRva',4),('forwardRva',6)]:
        r=p[key]
        if type(r) is not int or not 0<r<=16*1024*1024-length or (length==4 and r%4): raise ValueError('startup_return_range')
        if any(r<o+n and o<r+length for o,n in spans): raise ValueError('startup_return_overlap')
        spans.append((r,length))
    if not isinstance(p['protectReturnHex'],str) or not re.fullmatch('[0-9a-f]{32}',p['protectReturnHex']): raise ValueError('startup_return_prefix')
    module=p['systemModule']
    base=json.loads(parents[parent.SOURCES.index(loader_policy.SOURCE)])
    expected=next(m for m in base['modules'] if m['name']=='kernel32.dll')
    if type(module) is not dict or set(module)!={'name','bytes','sha256'} or type(module['bytes']) is not int or module!={k:expected[k] for k in module}: raise ValueError('startup_return_module')
    functions=[]
    for key in ['protectFunction','startupFunction']:
        f=p[key]
        if type(f) is not dict or set(f)!={'rva','prefixHex','preferredBase','highlowOffsets'}: raise ValueError('startup_return_function')
        if type(f['rva']) is not int or not 0<f['rva']<=16*1024*1024-20: raise ValueError('startup_return_function_rva')
        if not isinstance(f['prefixHex'],str) or not re.fullmatch('[0-9a-f]{40}',f['prefixHex']): raise ValueError('startup_return_function_prefix')
        if type(f['preferredBase']) is not int or not 0<f['preferredBase']<=0xffff0000 or f['preferredBase']%65536: raise ValueError('startup_return_base')
        offsets=f['highlowOffsets']
        if type(offsets) is not list or any(type(x) is not int or not 0<=x<=16 for x in offsets) or offsets!=sorted(set(offsets)) or any(b<a+4 for a,b in zip(offsets,offsets[1:])): raise ValueError('startup_return_fixups')
        functions.append(f'BootstrapExportSpec{{{f["rva"]}U,{parent.byte_array(f["prefixHex"])},{f["preferredBase"]}U,{sum(1<<i for i in offsets)}U}}')
    a,b=p['protectFunction']['rva'],p['startupFunction']['rva']
    if a<b+20 and b<a+20: raise ValueError('startup_return_function_overlap')
    return '\n'.join(['// Generated by tools/startup_return_policy.py. Do not edit.','#pragma once',
        '#include "saex/engine/startup_return.hpp"','#include "saex/engine/frame_target_policy.generated.hpp"','namespace saex::engine {',
        f'static_assert(reviewed_frame_policy_digest == "{p["framePolicySha256"]}");',
        'static_assert(startup_image_protections == std::array<std::uint32_t,2>{64,128});',
        f'inline constexpr std::string_view reviewed_startup_return_id = "{p["id"]}";',
        f'inline constexpr std::string_view reviewed_startup_return_digest = "{hashlib.sha256(data).hexdigest()}";',
        f'inline constexpr StartupReturnSpec reviewed_startup_return_spec{{{p["protectCallRva"]}U,{p["protectSlotRva"]}U,{p["startupSlotRva"]}U,{p["forwardRva"]}U,{parent.byte_array(p["protectReturnHex"])},{functions[0]},{functions[1]},reviewed_frame_spec}};',
        '}',''])

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    paths=[ROOT/p for p in SOURCES]
    if any(p.stat().st_size>65536 for p in paths): raise ValueError('startup_return_size')
    if not (ROOT/'docs/development/d1-startup-return.md').is_file(): raise ValueError('startup_return_review_missing')
    output=compile_source(*(p.read_bytes() for p in paths))
    if args.check:
        if not (ROOT/OUTPUT).is_file() or (ROOT/OUTPUT).read_text(encoding='utf-8')!=output: raise ValueError('stale_startup_return_output')
    else: (ROOT/OUTPUT).write_text(output,encoding='utf-8',newline='\n')
    print('Natural startup return policy verified.' if args.check else 'Natural startup return policy generated.')
if __name__=='__main__': main()
